<?php

namespace App\Services\OfficialKnowledgeParsing;

enum ParserDiagnosticCode: string
{
    case UNKNOWN_FIELD_HEADING = 'UNKNOWN_FIELD_HEADING';
    case MISSING_CODE = 'MISSING_CODE';
    case MISSING_CLASSIFICATION = 'MISSING_CLASSIFICATION';
    case NO_SOLUTION_STEPS = 'NO_SOLUTION_STEPS';
    case AMBIGUOUS_APPLICABILITY = 'AMBIGUOUS_APPLICABILITY';
    case MALFORMED_STEP_SEQUENCE = 'MALFORMED_STEP_SEQUENCE';
    case UNTERMINATED_SECTION = 'UNTERMINATED_SECTION';
    case CODE_MISMATCH = 'CODE_MISMATCH';
}
