<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\GovernanceController;
use App\Http\Controllers\Api\HealthController;
use App\Http\Controllers\Api\VersionController;
use App\Http\Controllers\Api\OperationsController;
use App\Http\Controllers\Api\ComponentsController;
use App\Http\Controllers\Api\InventoryController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->middleware('request.id')->group(function () {
    Route::get('health', HealthController::class);
    Route::get('version', VersionController::class);
    Route::middleware('web')->group(function () {
        Route::post('auth/login', [AuthController::class, 'login']);
        Route::middleware(['auth', 'active.user'])->group(function () {
            Route::post('auth/logout', [AuthController::class, 'logout']);
            Route::get('me', [AuthController::class, 'me']);
            Route::get('accounts', [GovernanceController::class, 'accounts']);
            Route::post('accounts', [GovernanceController::class, 'storeAccount']);
            Route::put('accounts/{id}', [GovernanceController::class, 'updateAccount']);
            Route::get('accounts/{id}/branches', [GovernanceController::class, 'branches']);
            Route::post('accounts/{id}/branches', [GovernanceController::class, 'storeBranch']);
            Route::put('accounts/{accountId}/branches/{id}', [GovernanceController::class, 'updateBranch']);
            Route::get('accounts/{id}/members', [GovernanceController::class, 'members']);
            Route::post('accounts/{id}/members', [GovernanceController::class, 'provision']);
            Route::patch('accounts/{accountId}/members/{id}', [GovernanceController::class, 'updateMember']);
            Route::post('platform/bootstrap-superuser', [GovernanceController::class, 'bootstrap']);
            Route::get('manufacturers', [OperationsController::class, 'manufacturers']);
            Route::post('manufacturers', [OperationsController::class, 'storeManufacturer']);
            Route::patch('manufacturers/{id}/status', [OperationsController::class, 'setManufacturerStatus']);
            Route::get('machine-models', [OperationsController::class, 'models']);
            Route::post('machine-models', [OperationsController::class, 'storeModel']);
            Route::patch('machine-models/{id}/status', [OperationsController::class, 'setModelStatus']);
            Route::get('branches/{branch}/machines', [OperationsController::class, 'machines']);
            Route::post('branches/{branch}/machines', [OperationsController::class, 'storeMachine']);
            Route::patch('machines/{id}/status', [OperationsController::class, 'setMachineStatus']);
            Route::get('machines/{id}', [OperationsController::class, 'machine']);
            Route::get('branches/{branch}/operational-people', [OperationsController::class, 'people']);
            Route::get('accounts/{account}/operational-people', [OperationsController::class, 'governancePeople']);
            Route::post('accounts/{account}/operational-people', [OperationsController::class, 'storePerson']);
            Route::patch('operational-people/{id}/status', [OperationsController::class, 'setPersonStatus']);
            Route::post('operational-people/{person}/branches/{branch}', [OperationsController::class, 'assignPerson']);
            Route::get('machines/{machine}/counters', [OperationsController::class, 'counters']);
            Route::post('machines/{machine}/counters', [OperationsController::class, 'createCounter']);
            Route::post('counter-readings/{reading}/correction', [OperationsController::class, 'correctCounter']);
            Route::get('machines/{machine}/counters/period', [OperationsController::class, 'period']);
            Route::get('components', [ComponentsController::class, 'catalogs']);
            Route::post('components', [ComponentsController::class, 'storeCatalog']);
            Route::patch('components/{id}/status', [ComponentsController::class, 'setCatalogStatus']);
            Route::get('machine-models/{model}/profiles', [ComponentsController::class, 'profiles']);
            Route::post('machine-models/{model}/profiles', [ComponentsController::class, 'storeProfile']);
            Route::post('model-profiles/{profile}/slots', [ComponentsController::class, 'storeSlot']);
            Route::patch('model-profiles/{id}/status', [ComponentsController::class, 'setProfileStatus']);
            Route::get('machines/{machine}/components', [ComponentsController::class, 'machineComponents']);
            Route::post('machines/{machine}/components/sync', [ComponentsController::class, 'sync']);
            Route::post('machines/{machine}/components/manual', [ComponentsController::class, 'add']);
            Route::post('machine-components/{component}/exclude', [ComponentsController::class, 'exclude']);
            Route::post('component-exclusions/{exclusion}/clear', [ComponentsController::class, 'clearExclusion']);
            Route::post('machine-components/{component}/lifecycles', [ComponentsController::class, 'initialize']);
            Route::get('inventory/items', [InventoryController::class, 'items']);
            Route::get('inventory/locations', [InventoryController::class, 'locations']);
            Route::post('purchases', [InventoryController::class, 'createPurchase']);
            Route::post('purchases/{purchase}/receive', [InventoryController::class, 'receive']);
            Route::get('inventory/items/{item}/locations/{location}/balance', [InventoryController::class, 'balance']);
            Route::post('inventory/transfers', [InventoryController::class, 'transfer']);
            Route::post('inventory/adjustments', [InventoryController::class, 'adjust']);
            Route::post('machine-components/{component}/replacements', [InventoryController::class, 'replace']);
        });
    });
});
