<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ComponentsController;
use App\Http\Controllers\Api\GovernanceController;
use App\Http\Controllers\Api\HealthController;
use App\Http\Controllers\Api\IncidentsController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\MachineCostController;
use App\Http\Controllers\Api\OperationsController;
use App\Http\Controllers\Api\ReportsController;
use App\Http\Controllers\Api\VersionController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->middleware('request.id')->group(function () {
    Route::get('health', HealthController::class);
    Route::get('version', VersionController::class);
    Route::middleware('web')->group(function () {
        Route::post('auth/login', [AuthController::class, 'login']);
        Route::middleware(['auth', 'active.user'])->group(function () {
            Route::post('auth/logout', [AuthController::class, 'logout']);
            Route::get('me', [AuthController::class, 'me']);
            Route::patch('me/account', [AuthController::class, 'updateAccount']);
            Route::get('accounts', [GovernanceController::class, 'accounts']);
            Route::post('accounts', [GovernanceController::class, 'storeAccount']);
            Route::put('accounts/{id}', [GovernanceController::class, 'updateAccount']);
            Route::get('accounts/{id}/branches', [GovernanceController::class, 'branches']);
            Route::get('accounts/{id}/settings', [GovernanceController::class, 'settings']);
            Route::patch('accounts/{id}/settings/policy', [GovernanceController::class, 'updatePolicy']);
            Route::post('accounts/{id}/branches', [GovernanceController::class, 'storeBranch']);
            Route::put('accounts/{accountId}/branches/{id}', [GovernanceController::class, 'updateBranch']);
            Route::get('accounts/{id}/members', [GovernanceController::class, 'members']);
            Route::post('accounts/{id}/members', [GovernanceController::class, 'provision']);
            Route::patch('accounts/{accountId}/members/{id}', [GovernanceController::class, 'updateMember']);
            Route::patch('accounts/{accountId}/members/{id}/email', [GovernanceController::class, 'updateMemberEmail']);
            Route::post('accounts/{accountId}/members/{id}/password', [GovernanceController::class, 'resetMemberPassword']);
            Route::post('platform/bootstrap-superuser', [GovernanceController::class, 'bootstrap']);
            Route::get('manufacturers', [OperationsController::class, 'manufacturers']);
            Route::post('manufacturers', [OperationsController::class, 'storeManufacturer']);
            Route::put('manufacturers/{id}', [OperationsController::class, 'updateManufacturer']);
            Route::patch('manufacturers/{id}/status', [OperationsController::class, 'setManufacturerStatus']);
            Route::get('machine-models', [OperationsController::class, 'models']);
            Route::post('machine-models', [OperationsController::class, 'storeModel']);
            Route::put('machine-models/{id}', [OperationsController::class, 'updateModel']);
            Route::patch('machine-models/{id}/status', [OperationsController::class, 'setModelStatus']);
            Route::get('branches/{branch}/machines', [OperationsController::class, 'machines']);
            Route::post('branches/{branch}/machines', [OperationsController::class, 'storeMachine']);
            Route::patch('machines/{id}/status', [OperationsController::class, 'setMachineStatus']);
            Route::patch('machines/{id}', [OperationsController::class, 'updateMachine']);
            Route::get('machines/{id}', [OperationsController::class, 'machine']);
            Route::get('branches/{branch}/operational-people', [OperationsController::class, 'people']);
            Route::get('accounts/{account}/operational-people', [OperationsController::class, 'governancePeople']);
            Route::post('accounts/{account}/operational-people', [OperationsController::class, 'storePerson']);
            Route::put('accounts/{account}/operational-people/{id}', [OperationsController::class, 'updatePerson']);
            Route::patch('operational-people/{id}/status', [OperationsController::class, 'setPersonStatus']);
            Route::post('operational-people/{person}/branches/{branch}', [OperationsController::class, 'assignPerson']);
            Route::get('machines/{machine}/counters', [OperationsController::class, 'counters']);
            Route::post('machines/{machine}/counters', [OperationsController::class, 'createCounter']);
            Route::post('counter-readings/{reading}/correction', [OperationsController::class, 'correctCounter']);
            Route::get('machines/{machine}/counters/period', [OperationsController::class, 'period']);
            Route::get('components', [ComponentsController::class, 'catalogs']);
            Route::post('components', [ComponentsController::class, 'storeCatalog']);
            Route::put('components/{id}', [ComponentsController::class, 'updateCatalog']);
            Route::patch('components/{id}/status', [ComponentsController::class, 'setCatalogStatus']);
            Route::get('machine-models/{model}/profiles', [ComponentsController::class, 'profiles']);
            Route::post('machine-models/{model}/profiles', [ComponentsController::class, 'storeProfile']);
            Route::post('model-profiles/{profile}/slots', [ComponentsController::class, 'storeSlot']);
            Route::patch('model-profiles/{id}/status', [ComponentsController::class, 'setProfileStatus']);
            Route::get('machines/{machine}/components', [ComponentsController::class, 'machineComponents']);
            Route::post('machines/{machine}/components/sync', [ComponentsController::class, 'sync']);
            Route::post('machines/{machine}/components/manual', [ComponentsController::class, 'add']);
            Route::post('machine-components/{component}/exclude', [ComponentsController::class, 'exclude']);
            Route::post('component-exclusions/{exclusion}/clear', [ComponentsController::class, 'clearExclusion']);
            Route::post('machine-components/{component}/lifecycles', [ComponentsController::class, 'initialize']);
            Route::post('machine-components/{component}/reconcile', [ComponentsController::class, 'reconcile']);
            Route::patch('machine-components/{component}', [ComponentsController::class, 'remove']);
            Route::get('machine-components/{component}/reconciliation-candidate', [ComponentsController::class, 'reconciliationCandidate']);
            Route::get('inventory/items', [InventoryController::class, 'items']);
            Route::get('accounts/{account}/branches/{branch}/inventory', [InventoryController::class, 'workspace']);
            Route::get('inventory/suppliers', [InventoryController::class, 'suppliers']);
            Route::post('inventory/suppliers', [InventoryController::class, 'saveSupplier']);
            Route::put('inventory/suppliers/{id}', [InventoryController::class, 'saveSupplier']);
            Route::delete('inventory/suppliers/{id}', [InventoryController::class, 'deleteSupplier']);
            Route::post('inventory/items', [InventoryController::class, 'saveItem']);
            Route::put('inventory/items/{id}', [InventoryController::class, 'saveItem']);
            Route::patch('inventory/items/{id}', [InventoryController::class, 'deleteItem']);
            Route::post('inventory/locations', [InventoryController::class, 'saveLocation']);
            Route::put('inventory/locations/{id}', [InventoryController::class, 'saveLocation']);
            Route::patch('inventory/locations/{id}', [InventoryController::class, 'deleteLocation']);
            Route::get('inventory/locations', [InventoryController::class, 'locations']);
            Route::post('purchases', [InventoryController::class, 'createPurchase']);
            Route::post('purchases/{purchase}/receive', [InventoryController::class, 'receive']);
            Route::post('inventory/opening', [InventoryController::class, 'opening']);
            Route::get('inventory/items/{item}/locations/{location}/balance', [InventoryController::class, 'balance']);
            Route::post('inventory/transfers', [InventoryController::class, 'transfer']);
            Route::post('inventory/adjustments', [InventoryController::class, 'adjust']);
            Route::post('machine-components/{component}/replacements', [InventoryController::class, 'replace']);
            Route::get('accounts/{account}/branches/{branch}/incidents', [IncidentsController::class, 'index']);
            Route::post('accounts/{account}/branches/{branch}/incidents', [IncidentsController::class, 'store']);
            Route::get('accounts/{account}/branches/{branch}/incidents/{incident}', [IncidentsController::class, 'show']);
            Route::patch('incidents/{incident}', [IncidentsController::class, 'update']);
            Route::post('incidents/{incident}/solve', [IncidentsController::class, 'solve']);
            Route::post('incidents/{incident}/void', [IncidentsController::class, 'void']);
            Route::get('machines/{machine}/cost', [MachineCostController::class, 'show']);
            Route::post('machines/{machine}/cost/selling-prices', [MachineCostController::class, 'createSellingPrice']);
            Route::post('selling-prices/{price}/void', [MachineCostController::class, 'voidSellingPrice']);
            Route::post('machines/{machine}/cost/operating-costs', [MachineCostController::class, 'createOperatingCost']);
            Route::post('operating-costs/{cost}/void', [MachineCostController::class, 'voidOperatingCost']);
            Route::get('reports', ReportsController::class);
        });
    });
});
