import { useState } from 'react'
import { createPortal } from 'react-dom'
import { Boxes, LoaderCircle, RotateCcw, X } from 'lucide-react'
import { useAuth } from '../auth/useAuth.js'
import { createDraftKey } from '../drafts/draftKeys.js'
import { usePersistentDraft } from '../drafts/usePersistentDraft.js'

const blank = { code: '', name: '', category: '', description: '', manufacturerId: '', partNumber: '', trackingMethod: 'counter_based' }
const isDraft = (v) => v && typeof v.code === 'string' && typeof v.name === 'string' && typeof v.trackingMethod === 'string'

export function ComponentDialog({ account, component, manufacturers, onClose, onSave }) {
  const { user } = useAuth()
  const initial = component ? { code: component.code, name: component.name, category: component.category ?? '', description: component.description ?? '', manufacturerId: component.manufacturer_id ?? '', partNumber: component.part_number ?? '', trackingMethod: component.default_tracking_method } : blank
  const { value, updateDraft, clearDraft, resetDraft, hasDraft, wasRestored } = usePersistentDraft({
    draftKey: createDraftKey({ userId: user.id, accountId: account.id, feature: 'component-catalog', entityId: component?.id ?? 'new' }),
    initialValue: initial, metadata: { baseUpdatedAt: component?.updated_at ?? null }, validate: isDraft,
  })
  const [error, setError] = useState(null); const [saving, setSaving] = useState(false)
  const change = (field, next) => updateDraft((current) => ({ ...current, [field]: next }))
  async function submit(event) { event.preventDefault(); if (!value.name.trim() || !value.code.trim()) return setError('Code and name are required.'); setSaving(true); setError(null); try { await onSave(value); clearDraft(); onClose() } catch (e) { setError(e.message) } finally { setSaving(false) } }
  return createPortal(<div className="dialog-backdrop"><section className="machine-dialog component-dialog glass-surface" role="dialog" aria-modal="true"><header className="dialog-header"><div className="dialog-heading"><span className="dialog-icon"><Boxes size={22}/></span><div><span className="card-kicker">Component catalog</span><h2>{component ? 'Edit component' : 'Add component'}</h2><p>Reusable definition for one or more machine models.</p></div></div><button className="icon-button" onClick={onClose} disabled={saving} aria-label="Close"><X size={19}/></button></header><form className="machine-form" onSubmit={submit}><div className="machine-form-body">{wasRestored && <div className="draft-restored-status">Unsaved draft restored</div>}<div className="form-grid"><label className="form-field"><span>Code *</span><input value={value.code} onChange={(e)=>change('code',e.target.value)} placeholder="FUSER_BELT"/></label><label className="form-field"><span>Name *</span><input value={value.name} onChange={(e)=>change('name',e.target.value)} placeholder="Fuser Belt"/></label><label className="form-field"><span>Category</span><input value={value.category} onChange={(e)=>change('category',e.target.value)}/></label><label className="form-field"><span>Manufacturer</span><select value={value.manufacturerId} onChange={(e)=>change('manufacturerId',e.target.value)}><option value="">Any manufacturer</option>{manufacturers.map((m)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="form-field"><span>Part number</span><input value={value.partNumber} onChange={(e)=>change('partNumber',e.target.value)}/></label><label className="form-field"><span>Default tracking</span><select value={value.trackingMethod} onChange={(e)=>change('trackingMethod',e.target.value)}><option value="counter_based">Counter based</option><option value="consumption_based">Consumption based</option><option value="inspection_based">Inspection based</option></select></label><label className="form-field form-field-wide"><span>Description</span><textarea value={value.description} onChange={(e)=>change('description',e.target.value)} rows="3"/></label></div>{error && <div className="form-error">{error}</div>}</div><footer className="dialog-actions"><button className="draft-reset-button" type="button" onClick={()=>resetDraft(initial)} disabled={!hasDraft}><RotateCcw size={15}/>Reset draft</button><button className="secondary-button" type="button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving&&<LoaderCircle className="spin" size={16}/>}Save component</button></footer></form></section></div>, document.body)
}
