import { CircleDollarSign, Plus, RotateCcw } from 'lucide-react'
import { categoryLabels } from './operatingCostModel.js'
import { formatIdrTotal } from './currencyFormat.js'

const date = (value) => value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium' }).format(new Date(value)) : '—'

export function OperatingCostsPanel({ costs, canManage, enabled, onAdd, onVoid }) {
  return <section className="machine-cost-panel glass-surface operating-cost-panel"><header><div><span className="card-kicker">Advanced Machine Economics</span><h2>Advanced Operating Costs</h2><p>Non-inventory costs directly attributable to this machine. Posted records are immutable.</p></div>{enabled && canManage && <button className="primary-button" type="button" onClick={onAdd}><Plus size={16} />Add Operating Cost</button>}</header>
    {!enabled && <div className="advanced-feature-disabled" role="status"><CircleDollarSign size={24} /><div><strong>Advanced Operating Costs are disabled for this account.</strong><span>Enable this feature when the business is ready to track electricity, manpower, service allocation, depreciation, lease, and other attributable operating costs.</span>{costs.length > 0 && <small>Historical records remain readable below and are never deleted by this setting.</small>}</div></div>}
    {!costs.length ? <div className="machine-cost-empty"><CircleDollarSign size={25} /><strong>{enabled ? 'No advanced operating-cost history for this machine.' : 'No historical advanced operating-cost records for this machine.'}</strong><span>No service, electricity, labor, or other cost is fabricated.</span></div> : <div className="operating-cost-list">{costs.map((cost) => <article key={cost.id} className={cost.status === 'voided' ? 'is-voided' : ''}><div><strong>{categoryLabels[cost.category]}</strong><span>{cost.description}</span></div><div><span>{cost.allocation_method === 'one_time' ? date(cost.effective_at) : `${cost.period_start} → ${cost.period_end}`}</span><small>{cost.allocation_method === 'one_time' ? 'One-time' : 'Daily proration v1'} · {cost.source_type}</small></div><div><strong>{formatIdrTotal(cost.amount)}</strong><span>{cost.external_reference || 'No external reference'}</span></div><div><span className={`incident-status-pill ${cost.status === 'posted' ? 'resolved' : 'voided'}`}>{cost.status}</span>{enabled && canManage && cost.status === 'posted' && <button className="secondary-button" type="button" onClick={() => onVoid(cost)}><RotateCcw size={14} />Void</button>}</div></article>)}</div>}
  </section>
}
