import { useEffect, useMemo, useState } from 'react'
import { Archive, Boxes, Edit3, Plus, RefreshCcw, ShieldCheck, Trash2 } from 'lucide-react'
import { PageHeader } from '../components/ui/PageHeader.jsx'
import { useAuth } from '../features/auth/useAuth.js'
import { useTenant } from '../features/account/useTenant.js'
import { ComponentDialog } from '../features/components/ComponentDialog.jsx'
import { ProfileDialog } from '../features/components/ProfileDialog.jsx'
import { useComponentWorkflowState } from '../features/components/useComponentWorkflowState.js'
import { createUIStateKey } from '../features/uiState/uiStateKeys.js'
import { usePersistentUIState } from '../features/uiState/usePersistentUIState.js'
import { deleteComponent, effectiveProfiles, loadComponentFoundation, removeProfile, saveComponent, saveProfile } from '../services/supabase/components.js'

const trackingLabels = { counter_based: 'Counter based', consumption_based: 'Consumption based', inspection_based: 'Inspection based' }
const validView = (v) => v && ['profiles','catalog'].includes(v.tab) && (v.modelId == null || typeof v.modelId === 'string') && typeof v.showArchived === 'boolean'

function ConfirmDialog({ title, message, confirmLabel, onCancel, onConfirm, busy }) {
  return <div className="dialog-backdrop"><section className="confirm-dialog glass-surface" role="alertdialog" aria-modal="true"><span className="danger-dialog-icon"><Trash2 size={22}/></span><h2>{title}</h2><p>{message}</p><div className="dialog-actions"><button className="secondary-button" onClick={onCancel} disabled={busy}>Cancel</button><button className="danger-button" onClick={onConfirm} disabled={busy}>{busy?'Working…':confirmLabel}</button></div></section></div>
}

export function ComponentsPage() {
  const { user } = useAuth(); const { account, membership } = useTenant(); const canManage = ['owner','admin'].includes(membership?.role)
  const [data,setData]=useState({manufacturers:[],models:[],components:[],profiles:[]}); const [loading,setLoading]=useState(true); const [error,setError]=useState(null); const [notice,setNotice]=useState(null); const [confirm,setConfirm]=useState(null); const [busy,setBusy]=useState(false)
  const key=createUIStateKey({userId:user.id,accountId:account.id,feature:'components-view',entityId:'active'})
  const {value:view,setUIState:setView}=usePersistentUIState({uiStateKey:key,initialValue:{tab:'profiles',modelId:null,showArchived:false},validate:validView})
  const {workflow,open,close}=useComponentWorkflowState({userId:user.id,accountId:account.id})
  async function refresh(){setLoading(true);setError(null);try{setData(await loadComponentFoundation())}catch(e){setError(e)}finally{setLoading(false)}}
  useEffect(()=>{refresh()},[])
  const selectedModel=data.models.find((m)=>m.id===view.modelId)??data.models[0]??null
  useEffect(()=>{if(!view.modelId&&data.models[0])setView((v)=>({...v,modelId:data.models[0].id}))},[data.models,view.modelId,setView])
  const effective=useMemo(()=>effectiveProfiles(data.profiles,account.id,selectedModel?.id),[account.id,data.profiles,selectedModel?.id])
  const visibleProfiles=effective.filter((p)=>view.showArchived?!p.is_active:p.is_active)
  const visibleComponents=data.components.filter((c)=>view.showArchived?!c.is_active:c.is_active)
  const editingComponent=data.components.find((c)=>c.id===workflow.entityId); const editingProfile=effective.find((p)=>p.id===workflow.entityId)
  async function savedComponent(values){await saveComponent({accountId:account.id,component:editingComponent,values});await refresh();setNotice('Component saved.')}
  async function savedProfile(values){await saveProfile({accountId:account.id,modelId:selectedModel.id,profile:editingProfile,values});await refresh();setNotice('Model profile saved. Future lifecycle installs will use the updated baseline.')}
  async function runConfirm(){setBusy(true);try{const result=confirm.kind==='component'?await deleteComponent({accountId:account.id,componentId:confirm.item.id}):await removeProfile({accountId:account.id,modelId:selectedModel.id,profile:confirm.item});setNotice(result.mode==='deleted'?'Unused record permanently deleted.':'Historical safety required archiving; the record remains readable.');setConfirm(null);await refresh()}catch(e){setError(e)}finally{setBusy(false)}}
  const action=canManage?<div className="page-header-actions"><button className="secondary-button" onClick={()=>open('component-create')}><Plus size={17}/>Add Component</button>{selectedModel&&<button className="primary-button" onClick={()=>open('profile-create')}><Plus size={17}/>Add to Model</button>}</div>:null
  return <div className="page-stack"><PageHeader eyebrow={`${account.name} · Component intelligence`} title="Components" description="Reusable catalog definitions and editable machine-model component profiles. No lifecycle or health data is created here." action={action}/>{notice&&<div className="success-banner"><span>{notice}</span><button onClick={()=>setNotice(null)}>Dismiss</button></div>}{!canManage&&<div className="permission-banner"><ShieldCheck size={18}/><span>Your {membership?.role} role has read-only access. Owners and admins manage catalog and profiles.</span></div>}{error&&<div className="inline-error catalog-error"><span>{error.message}</span><button className="secondary-button" onClick={refresh}>Try again</button></div>}
  <section className="component-shell glass-surface"><div className="component-toolbar"><div className="machine-view-tabs"><button className={view.tab==='profiles'?'selected':''} onClick={()=>setView((v)=>({...v,tab:'profiles'}))}>Model Profiles</button><button className={view.tab==='catalog'?'selected':''} onClick={()=>setView((v)=>({...v,tab:'catalog'}))}>Component Catalog</button></div><button className="icon-button" onClick={refresh} aria-label="Refresh"><RefreshCcw size={17} className={loading?'spin':''}/></button></div>
  {view.tab==='profiles'&&<><div className="model-selector-row"><label><span>Machine model</span><select value={selectedModel?.id??''} onChange={(e)=>setView((v)=>({...v,modelId:e.target.value}))}>{data.models.map((m)=><option key={m.id} value={m.id}>{m.manufacturers?.name} · {m.name}</option>)}</select></label><div><strong>{effective.filter((p)=>p.is_active).length}</strong><span>active profiles</span></div></div><div className="machine-view-tabs record-tabs"><button className={!view.showArchived?'selected':''} onClick={()=>setView((v)=>({...v,showArchived:false}))}>Active <span>{effective.filter((p)=>p.is_active).length}</span></button><button className={view.showArchived?'selected':''} onClick={()=>setView((v)=>({...v,showArchived:true}))}>Archived <span>{effective.filter((p)=>!p.is_active).length}</span></button></div><div className="component-table-head"><span>Component / slot</span><span>Tracking</span><span>Baseline</span><span>Adaptive</span><span>Actions</span></div><div className="component-list">{visibleProfiles.map((p)=><article className="component-row" key={p.id}><div className="component-identity"><span className="component-icon"><Boxes size={18}/></span><div><strong>{p.components?.name}</strong><code>{p.slot_code}</code></div></div><span className="tracking-pill">{trackingLabels[p.tracking_method]}</span><div className="component-baseline"><strong>{p.baseline_expected_clicks?.toLocaleString()??'Reference only'}</strong><span>expected clicks</span></div><span className={p.adaptive_enabled?'adaptive-on':'adaptive-off'}>{p.adaptive_enabled?'Enabled':'Disabled'}</span><div className="row-actions">{canManage&&<><button onClick={()=>open('profile-edit',p.id)} aria-label={`Edit ${p.components?.name}`}><Edit3 size={16}/></button><button onClick={()=>setConfirm({kind:'profile',item:p})} aria-label={`Remove ${p.components?.name}`}>{p.is_active?<Archive size={16}/>:<Trash2 size={16}/>}</button></>}</div></article>)}</div></>}
  {view.tab==='catalog'&&<><div className="catalog-summary"><div><span className="card-kicker">Reusable definitions</span><h2>{visibleComponents.length} {view.showArchived?'archived':'active'} components</h2></div><div className="machine-view-tabs"><button className={!view.showArchived?'selected':''} onClick={()=>setView((v)=>({...v,showArchived:false}))}>Active</button><button className={view.showArchived?'selected':''} onClick={()=>setView((v)=>({...v,showArchived:true}))}>Archived</button></div></div><div className="catalog-grid">{visibleComponents.map((c)=><article className="catalog-card" key={c.id}><div><span className="component-icon"><Boxes size={18}/></span><span className={c.account_id?'scope-pill custom':'scope-pill'}>{c.account_id?'Workspace':'Shared'}</span></div><h3>{c.name}</h3><code>{c.code}</code><p>{c.category??'Uncategorized'} · {trackingLabels[c.default_tracking_method]}</p>{canManage&&c.account_id===account.id&&<div className="catalog-actions"><button className="secondary-button" onClick={()=>open('component-edit',c.id)}><Edit3 size={15}/>Edit</button><button className="secondary-button" onClick={()=>setConfirm({kind:'component',item:c})}><Trash2 size={15}/>Delete</button></div>}</article>)}</div></>}
  {!loading&&((view.tab==='profiles'&&!visibleProfiles.length)||(view.tab==='catalog'&&!visibleComponents.length))&&<div className="component-empty">No records in this view.</div>}{loading&&<div className="machine-loading-state"><RefreshCcw className="spin" size={24}/><strong>Loading component intelligence…</strong></div>}</section>
  {canManage&&(workflow.type==='component-create'||(workflow.type==='component-edit'&&editingComponent))&&<ComponentDialog account={account} component={editingComponent} manufacturers={data.manufacturers} onClose={close} onSave={savedComponent}/>} {canManage&&selectedModel&&(workflow.type==='profile-create'||(workflow.type==='profile-edit'&&editingProfile))&&<ProfileDialog account={account} model={selectedModel} profile={editingProfile} components={data.components} onClose={close} onSave={savedProfile}/>} {confirm&&<ConfirmDialog title={confirm.kind==='component'?'Delete Component':'Remove Model Profile'} message={confirm.kind==='component'?'If this component has never been referenced, it will be permanently deleted. Historical usage forces a safe archive instead.':'Unused profiles are deleted. Any historically referenced profile is archived so operational records remain intact.'} confirmLabel={confirm.kind==='component'?'Delete / archive':'Remove / archive'} onCancel={()=>setConfirm(null)} onConfirm={runConfirm} busy={busy}/>}</div>
}
