import { createElement, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, BarChart3, Boxes, CalendarRange, Download, Gauge, Printer, RefreshCcw, Users } from 'lucide-react'
import { PageHeader } from '../components/ui/PageHeader.jsx'
import { Pagination } from '../components/ui/Pagination.jsx'
import { usePagination } from '../features/pagination/usePagination.js'
import { buildReportExport, downloadCsv } from '../features/reports/reportExport.js'
import { removePersistedReportBranch, reportStatus, reportTabs, validReportFilters } from '../features/reports/reportModel.js'
import { useAuth } from '../features/auth/useAuth.js'
import { useTenant } from '../features/account/useTenant.js'
import { machineCostPeriodPresets, resolveMachineCostPeriod } from '../features/machineCost/machineCostPeriods.js'
import { createUIStateKey } from '../features/uiState/uiStateKeys.js'
import { usePersistentUIState } from '../features/uiState/usePersistentUIState.js'
import { userErrorMessage } from '../lib/appErrors.js'
import { loadMachines } from '../services/supabase/machines.js'
import { loadOperationalReport } from '../services/supabase/reports.js'

const idr = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 2 })
const numeric = new Intl.NumberFormat('en-US', { maximumFractionDigits: 4 })
const money = (value) => value == null ? '—' : idr.format(Number(value))
const count = (value) => value == null ? '—' : numeric.format(Number(value))
const dateTime = (value, timezone) => value ? new Date(value).toLocaleString('id-ID', { timeZone: timezone }) : '—'

function ReportKpi({ icon, label, value, hint, tone = 'blue' }) { return <article className="report-kpi glass-surface"><span className={`report-kpi-icon tone-${tone}`}>{createElement(icon, { size: 19 })}</span><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></article> }
function EmptyReport({ title, detail }) { return <div className="report-empty glass-surface"><BarChart3 size={26} /><strong>{title}</strong><span>{detail}</span></div> }
function StatusBadge({ status }) { const [label, tone] = reportStatus(status); return <span className={`report-status tone-${tone}`} role="status">{label}</span> }
function RankingChart({ title, description, rows, valueKey, label, formatValue = money, tone = 'blue' }) { const maximum = Math.max(0, ...rows.map((row) => Math.abs(Number(row[valueKey] ?? 0)))); return <section className="report-chart glass-surface" aria-label={`${title}. ${rows.length} plotted points.`}><header><div><span className="card-kicker">Operational evidence</span><h2>{title}</h2><p>{description}</p></div></header>{rows.length ? <div className="report-ranking">{rows.map((row) => <div key={row.key ?? `${label(row)}-${row[valueKey]}`}><div><strong>{label(row)}</strong><span>{formatValue(row[valueKey])}</span></div><span className="report-rank-track"><i className={`tone-${tone}`} style={{ width: `${maximum ? Math.abs(Number(row[valueKey] ?? 0)) / maximum * 100 : 0}%` }} /></span></div>)}</div> : <div className="report-chart-empty">No chart evidence for this period.</div>}</section> }
function ReportList({ headers, rows, renderRow, emptyTitle, emptyDetail, resetKey }) { const pagination = usePagination(rows.length, resetKey); if (!rows.length) return <EmptyReport title={emptyTitle} detail={emptyDetail} />; return <div className="report-table-wrap glass-surface" role="table" aria-label={emptyTitle.replace(/^No /, '')}><div className="report-table-head" role="row" style={{ '--report-columns': headers.length }}>{headers.map((header) => <span role="columnheader" key={header}>{header}</span>)}</div><div className="report-table-body" role="rowgroup">{rows.slice(pagination.start, pagination.end).map(renderRow)}</div><Pagination total={rows.length} {...pagination} onPageChange={pagination.setPage} onPageSizeChange={pagination.setPageSize} label="report evidence" /></div> }
function SectionHeading({ kicker, title, detail, status, children }) { return <div className="report-section-heading"><div><span className="card-kicker">{kicker}</span><h2>{title}</h2><p>{detail}</p></div>{status ? <StatusBadge status={status} /> : children}</div> }
// Kept as a compatibility seam for the existing pagination contract tests;
// period comparison is now represented by the canonical overview projection.
function PeriodComparison() { return null }

export function ReportsPage() {
  const { user } = useAuth(); const { account, branch } = useTenant()
  const stateKey = createUIStateKey({ userId: user.id, accountId: account.id, feature: 'reports-filters', entityId: 'workspace' })
  const { value: filters, setUIState: setFilters } = usePersistentUIState({ uiStateKey: stateKey, initialValue: { tab: 'overview', machineId: '', preset: 'this_month', customStart: '', customEnd: '', errorCategory: '', errorStatus: '' }, validate: validReportFilters })
  const [machines, setMachines] = useState([]); const [report, setReport] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const requestId = useRef(0)
  const selectedMachine = machines.find((machine) => machine.id === filters.machineId) ?? null; const timezone = selectedMachine?.timezone || branch?.timezone || account.default_timezone || 'UTC'
  const period = useMemo(() => resolveMachineCostPeriod({ preset: filters.preset, timezone, customStart: filters.customStart, customEnd: filters.customEnd }), [filters.customEnd, filters.customStart, filters.preset, timezone]); const validPeriod = Boolean(period.start && period.end && period.start <= period.end); const resetKey = `${branch?.id}:${filters.tab}:${filters.machineId}:${period.start}:${period.end}:${filters.errorCategory}:${filters.errorStatus}`
  useEffect(() => { let active = true; setMachines([]); if (branch?.id) loadMachines({ accountId: account.id, branchId: branch.id }).then((rows) => { if (active) setMachines(rows.filter((machine) => machine.is_active)) }).catch((loadError) => { if (active) setError(loadError) }); return () => { active = false } }, [account.id, branch?.id])
  useEffect(() => { if (Object.hasOwn(filters, 'branchId')) setFilters((current) => removePersistedReportBranch(current)) }, [filters, setFilters]); useEffect(() => { if (filters.machineId && !machines.some((machine) => machine.id === filters.machineId)) setFilters((current) => ({ ...current, machineId: '' })) }, [filters.machineId, machines, setFilters])
  const refresh = useCallback(async () => { const current = ++requestId.current; if (!validPeriod || !branch?.id) { setLoading(false); return }; setLoading(true); setError(null); try { const next = await loadOperationalReport({ accountId: account.id, branchId: branch.id, machineId: filters.machineId, periodStart: period.start, periodEnd: period.end, periodPreset: filters.preset, errorCategory: filters.errorCategory, errorStatus: filters.errorStatus }); if (requestId.current === current) setReport(next) } catch (loadError) { if (requestId.current === current) setError(loadError) } finally { if (requestId.current === current) setLoading(false) } }, [account.id, branch?.id, filters.errorCategory, filters.errorStatus, filters.machineId, filters.preset, period.end, period.start, validPeriod])
  useEffect(() => { refresh() }, [refresh])
  const overview = report?.overview; const incidentLoss = Number(overview?.machine_attributed_error_waste ?? 0) + Number(overview?.branch_only_error_waste ?? 0); const counterRows = report?.counter ?? []; const incidentRows = report?.incidents ?? report?.errors ?? []; const replacementRows = report?.replacements ?? []; const operatorRows = report?.operatorActivity ?? report?.operator_activity ?? []; const consumptionRows = report?.inventoryConsumption ?? report?.inventory_consumption ?? []; const machineCostRows = report?.economics ?? report?.machine_cost ?? []; const comparisonRows = report?.machineComparison ?? machineCostRows; const replacementCount = replacementRows.length || report?.components?.reduce((sum, row) => sum + Number(row.replacement_count || 0), 0) || 0; const machineIncidentCount = incidentRows.filter((row) => row.machine_id && row.status !== 'voided').length
  const handleExport = () => downloadCsv(buildReportExport({ tab: filters.tab, report, periodStart: period.start, periodEnd: period.end, branchLabel: branch?.code, machineLabel: selectedMachine?.machine_code }))
  return <div className="page-stack reports-page"><PageHeader eyebrow="Canonical operational analytics" title="Reports" description="Read-only usage, machine cost, replacement, incident, operator, and inventory-consumption evidence." /><section className="report-filter-bar glass-surface" aria-label="Global report filters"><label><span>Machine</span><select value={filters.machineId} onChange={(event) => setFilters((current) => ({ ...current, machineId: event.target.value }))}><option value="">{machines.length ? `All Machines in ${branch?.name}` : `No active machines in ${branch?.name}`}</option>{machines.map((machine) => <option value={machine.id} key={machine.id}>{machine.machine_code} · {machine.display_name}</option>)}</select></label><label><span>Period</span><select value={filters.preset} onChange={(event) => setFilters((current) => ({ ...current, preset: event.target.value }))}>{machineCostPeriodPresets.map((preset) => <option value={preset.id} key={preset.id}>{preset.label}</option>)}</select></label>{filters.preset === 'custom' && <><label><span>Start</span><input type="date" value={filters.customStart} onChange={(event) => setFilters((current) => ({ ...current, customStart: event.target.value }))} /></label><label><span>End</span><input type="date" min={filters.customStart || undefined} value={filters.customEnd} onChange={(event) => setFilters((current) => ({ ...current, customEnd: event.target.value }))} /></label></>}<div className="report-period"><CalendarRange size={16} /><span>{validPeriod ? `${period.start} → ${period.end}` : 'Choose a valid range'}<small>{timezone} operational timezone</small></span></div><button className="secondary-button" type="button" onClick={refresh} disabled={loading || !validPeriod}><RefreshCcw size={15} />Refresh</button></section><div className="report-action-bar"><span>Branch: {branch?.name ?? 'Unavailable'} · read-only projections</span><div><button className="secondary-button" type="button" onClick={handleExport} disabled={!report || loading}><Download size={15} />Export CSV</button><button className="secondary-button" type="button" onClick={() => window.print()} disabled={!report || loading}><Printer size={15} />Print / Save PDF</button></div></div><nav className="report-tabs" role="tablist" aria-label="Report sections">{reportTabs.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={filters.tab === tab.id} className={filters.tab === tab.id ? 'active' : ''} onClick={() => setFilters((current) => ({ ...current, tab: tab.id }))}>{tab.label}</button>)}</nav>{error && <div className="inline-error" role="alert">{userErrorMessage(error, 'Reports could not be generated for this scope.')}</div>}{loading ? <div className="report-loading glass-surface"><RefreshCcw className="spin" size={23} /><strong>Building report projections…</strong></div> : !report ? <EmptyReport title="Report unavailable" detail="Choose a valid report range and try again." /> : <>
    {filters.tab === 'overview' && <><SectionHeading kicker="Overview" title="Operational Summary" detail="Full-period KPIs remain independent of detailed-table pagination." status={overview?.report_status} /><section className="report-kpi-grid"><ReportKpi icon={Gauge} label="Total Clicks" value={count(overview?.total_clicks)} hint={`${overview?.active_machines ?? 0} active machines`} /><ReportKpi icon={Boxes} label="Component Cost" value={money(overview?.component_consumption_cost)} hint="Canonical consumed replacement evidence" tone="purple" /><ReportKpi icon={AlertTriangle} label="Error / Waste Loss" value={money(incidentLoss)} hint={`${money(overview?.machine_attributed_error_waste)} machine-attributed`} tone="warning" /><ReportKpi icon={BarChart3} label="Standard Machine Cost" value={money(overview?.standard_machine_cost)} hint="Component consumption + machine-attributed loss" /><ReportKpi icon={Gauge} label="Standard Cost / Click" value={money(overview?.standard_cost_per_click)} hint="Unavailable when period clicks are zero" tone="green" /><ReportKpi icon={Boxes} label="Replacement Count" value={count(replacementCount)} hint="Tracked and external replacement evidence" tone="purple" /><ReportKpi icon={AlertTriangle} label="Incident Count" value={count(incidentRows.length)} hint={`${machineIncidentCount} machine-attributed`} tone="warning" /></section><RankingChart title="Daily Click Trend" description="Canonical effective usage by operational date." rows={(report.dailyClicks ?? report.daily_clicks ?? []).map((row) => ({ ...row, key: row.operational_date }))} valueKey="total_clicks" label={(row) => row.operational_date} formatValue={count} /><RankingChart title="Machine Cost Breakdown" description="Standard cost contains component consumption and machine-attributed Error / Waste only." rows={[{ key: 'component', label: 'Component Consumption', value: overview?.component_consumption_cost }, { key: 'loss', label: 'Error / Waste', value: overview?.machine_attributed_error_waste }]} valueKey="value" label={(row) => row.label} />{machines.length > 1 && <ReportList headers={['Machine','Clicks','Component Cost','Error / Waste','Standard Cost','Cost / Click']} rows={comparisonRows} resetKey={resetKey} emptyTitle="No machine comparison" emptyDetail="No comparable machine evidence exists in this period." renderRow={(row) => <article role="row" className="report-table-row" style={{ '--report-columns': 6 }} key={row.machine_id}><span data-label="Machine">{row.machine_code || row.machine_id}</span><span data-label="Clicks">{count(row.total_clicks ?? row.period_clicks)}</span><span data-label="Component Cost">{money(row.component_consumption_cost ?? row.known_consumption_cost)}</span><span data-label="Error / Waste">{money(row.error_waste_cost)}</span><span data-label="Standard Cost">{money(row.standard_machine_cost)}</span><span data-label="Cost / Click">{money(row.standard_cost_per_click ?? row.machine_cost_per_click)}</span></article>} />}</>}
    {filters.tab === 'counter' && <><SectionHeading kicker="Counter / Usage" title="Effective Counter Evidence" detail="Usage belongs to readings entered by the historical operator snapshot." /><section className="report-kpi-grid compact"><ReportKpi icon={Gauge} label="Total Clicks" value={count(overview?.total_clicks)} hint="Full filtered period" /><ReportKpi icon={Gauge} label="Latest Counter" value={count(report.performance?.[0]?.latest_counter)} hint="Latest effective reading" /><ReportKpi icon={BarChart3} label="Counter Entry Count" value={count(counterRows.length)} hint="Effective entries" /></section><RankingChart title="Daily Click Trend" description="Effective usage rows only; no fabricated boundary counters." rows={(report.dailyClicks ?? report.daily_clicks ?? []).map((row) => ({ ...row, key: row.operational_date }))} valueKey="total_clicks" label={(row) => row.operational_date} formatValue={count} /><ReportList headers={['Observed At','Machine','Operator','Counter','Usage','Shift']} rows={counterRows} resetKey={resetKey} emptyTitle="No counter readings in this period" emptyDetail="No effective counter evidence matches the selected scope." renderRow={(row) => <article role="row" className="report-table-row" style={{ '--report-columns': 6 }} key={row.reading_id}><span data-label="Observed At">{dateTime(row.observed_at, timezone)}</span><span data-label="Machine">{row.machine_code || '—'}</span><span data-label="Operator">{row.operator_name_snapshot || row.operator_name || 'Unassigned'}</span><span data-label="Counter">{count(row.reading_value ?? row.counter)}</span><span data-label="Usage">{count(row.usage)}</span><span data-label="Shift">{row.shift_code || row.shift || '—'}</span></article>} /></>}
    {filters.tab === 'machine-cost' && <><SectionHeading kicker="Machine Cost" title="Standard Operational Cost" detail="Advanced Economics remains deferred; incomplete replacement evidence stays visible." status={overview?.report_status} /><section className="report-kpi-grid"><ReportKpi icon={Boxes} label="Component Cost" value={money(overview?.component_consumption_cost)} hint="Known consumed cost" tone="purple" /><ReportKpi icon={AlertTriangle} label="Error / Waste Loss" value={money(overview?.machine_attributed_error_waste)} hint="Explicit machine attribution only" tone="warning" /><ReportKpi icon={BarChart3} label="Standard Machine Cost" value={money(overview?.standard_machine_cost)} hint="Canonical sum" /><ReportKpi icon={Gauge} label="Period Clicks" value={count(overview?.total_clicks)} hint="Effective usage rows" /><ReportKpi icon={Gauge} label="Standard Cost / Click" value={money(overview?.standard_cost_per_click)} hint="— when clicks are zero" tone="green" /></section><RankingChart title="Machine Cost Breakdown" description="No purchase, receipt, opening, or overhead values are included." rows={[{ key: 'component', label: 'Component Consumption', value: overview?.component_consumption_cost }, { key: 'loss', label: 'Error / Waste', value: overview?.machine_attributed_error_waste }]} valueKey="value" label={(row) => row.label} />{(report.machine_cost_trend ?? []).length > 0 && <RankingChart title="Machine Cost Trend" description="Backend-derived Standard Machine Cost by operational period." rows={report.machine_cost_trend.map((row) => ({ ...row, key: row.operational_date }))} valueKey="standard_machine_cost" label={(row) => row.operational_date} />}<ReportList headers={['Machine','Clicks','Component Cost','Error / Waste','Standard Cost','Cost / Click','Evidence']} rows={machineCostRows} resetKey={resetKey} emptyTitle="No machine cost evidence in this period" emptyDetail="No active machine belongs to this report scope." renderRow={(row) => <article role="row" className="report-table-row" style={{ '--report-columns': 7 }} key={row.machine_id}><span data-label="Machine">{row.machine_code || row.machine_id}</span><span data-label="Clicks">{count(row.total_clicks ?? row.period_clicks)}</span><span data-label="Component Cost">{money(row.component_consumption_cost ?? row.known_consumption_cost)}</span><span data-label="Error / Waste">{money(row.error_waste_cost)}</span><span data-label="Standard Cost">{money(row.standard_machine_cost)}</span><span data-label="Cost / Click">{money(row.standard_cost_per_click ?? row.machine_cost_per_click)}</span><span data-label="Evidence">{row.standard_economics_status || row.economics_status || 'Complete'}</span></article>} /></>}
    {filters.tab === 'replacements' && <><SectionHeading kicker="Component / Replacement" title="Replacement Activity" detail="External/untracked replacements remain visible with unknown cost." /><section className="report-kpi-grid compact"><ReportKpi icon={Boxes} label="Replacement Count" value={count(replacementCount)} hint="Full filtered period" tone="purple" /></section><ReportList headers={['Date','Machine','Component','Slot','Source','Consumed Cost','Lifecycle']} rows={replacementRows} resetKey={resetKey} emptyTitle="No replacement activity in this period" emptyDetail="No component replacement evidence matches the selected scope." renderRow={(row) => <article role="row" className="report-table-row" style={{ '--report-columns': 7 }} key={row.replacement_event_id || row.replacement_id}><span data-label="Date">{dateTime(row.replaced_at, timezone)}</span><span data-label="Machine">{row.machine_code || '—'}</span><span data-label="Component">{row.component_code ? `${row.component_code} · ${row.component_name}` : row.component || '—'}</span><span data-label="Slot">{row.slot_code_snapshot || row.slot_code || '—'}</span><span data-label="Source">{(row.inventory_source || row.source || 'unknown').replaceAll('_', ' ')}</span><span data-label="Consumed Cost">{money(row.consumed_cost)}</span><span data-label="Lifecycle">{row.new_lifecycle_status || row.lifecycle_id || 'Recorded'}</span></article>} /></>}
    {filters.tab === 'incidents' && <><SectionHeading kicker="Incident / Error / Waste" title="Operational Incident Evidence" detail="Operator and PIC Terlibat remain separate historical roles."><div className="report-inline-filters"><label><span>Category</span><select value={filters.errorCategory} onChange={(event) => setFilters((current) => ({ ...current, errorCategory: event.target.value }))}><option value="">All</option>{['kesesuaian','kualitas','desain','bahan','prosedur'].map((value) => <option key={value}>{value}</option>)}</select></label><label><span>Status</span><select value={filters.errorStatus} onChange={(event) => setFilters((current) => ({ ...current, errorStatus: event.target.value }))}><option value="">All</option>{['open','resolved','voided'].map((value) => <option key={value}>{value}</option>)}</select></label></div></SectionHeading><section className="report-kpi-grid compact"><ReportKpi icon={AlertTriangle} label="Incident Count" value={count(incidentRows.length)} hint="Includes branch-only evidence" tone="warning" /><ReportKpi icon={AlertTriangle} label="Machine-attributed Incidents" value={count(machineIncidentCount)} hint="Explicit machine attribution" tone="warning" /><ReportKpi icon={BarChart3} label="Assessed Loss" value={money(incidentLoss)} hint="Canonical assessed loss" /></section><ReportList headers={['Date','Machine','Operator','PIC Terlibat','Type / Category','Loss','Status']} rows={incidentRows} resetKey={resetKey} emptyTitle="No incidents in this period" emptyDetail="No Incident / Error / Waste evidence matches the selected filters." renderRow={(row) => <article role="row" className="report-table-row" style={{ '--report-columns': 7 }} key={row.incident_id}><span data-label="Date">{dateTime(row.occurred_at, timezone)}</span><span data-label="Machine">{row.machine_code || 'Branch only'}</span><span data-label="Operator">{row.operator || row.operator_name || 'Unassigned'}</span><span data-label="PIC Terlibat">{row.pic || row.responsible_name || 'Unassigned'}</span><span data-label="Type / Category">{row.incident_type} · {row.category}</span><span data-label="Loss">{money(row.assessed_loss)}</span><span data-label="Status">{row.status}</span></article>} /></>}
    {filters.tab === 'operators' && <><SectionHeading kicker="Operator Activity" title="Usage on Readings Entered by Operator" detail="Recorded Usage is attribution to counter-entry evidence, not a claim of personal production." /><ReportList headers={['Operator','Counter Entries','Recorded Usage','Last Counter Entry','Machine(s)']} rows={operatorRows} resetKey={resetKey} emptyTitle="No operator activity in this period" emptyDetail="No counter readings with historical operator evidence match this scope." renderRow={(row) => <article role="row" className="report-table-row" style={{ '--report-columns': 5 }} key={row.operator}><span data-label="Operator"><Users size={15} /> {row.operator}</span><span data-label="Counter Entries">{count(row.counter_entries)}</span><span data-label="Recorded Usage">{count(row.recorded_usage)}</span><span data-label="Last Counter Entry">{dateTime(row.last_counter_entry, timezone)}</span><span data-label="Machine(s)">{Array.isArray(row.machines) ? row.machines.join(', ') : row.machines || '—'}</span></article>} /></>}
    {filters.tab === 'consumption' && <><SectionHeading kicker="Inventory Consumption" title="Machine-linked Consumption" detail="Purchases, receipts, opening balances, and transfers are excluded." /><ReportList headers={['Date','Machine','Inventory Item','Component','Quantity Consumed','Consumed Cost','Replacement / Location']} rows={consumptionRows} resetKey={resetKey} emptyTitle="No inventory consumption in this period" emptyDetail="No machine-linked replacement consumption matches the selected scope." renderRow={(row) => <article role="row" className="report-table-row" style={{ '--report-columns': 7 }} key={row.replacement_event_id || row.replacement_id}><span data-label="Date">{dateTime(row.replaced_at || row.effective_date, timezone)}</span><span data-label="Machine">{row.machine_code || '—'}</span><span data-label="Inventory Item">{row.inventory_item_name || row.item || '—'}</span><span data-label="Component">{row.component_code || row.component || '—'}</span><span data-label="Quantity Consumed">{count(row.inventory_quantity ?? row.quantity_consumed)} {row.inventory_unit || ''}</span><span data-label="Consumed Cost">{money(row.consumed_cost)}</span><span data-label="Replacement / Location">{row.inventory_location_name || row.replacement_event_id || row.replacement_id || 'Recorded'}</span></article>} /></>}
  </>}</div>
}
