import { createElement, useCallback, useEffect, useMemo, useState } from 'react'
import { Archive, Boxes, Building2, Check, CircleDollarSign, Edit3, Factory, Gauge, History, LoaderCircle, MapPin, Package, Plus, RefreshCcw, RotateCcw, Settings2, ShieldCheck, UserRound, Users, Workflow, X } from 'lucide-react'
import { BlockingDialog } from '../components/ui/BlockingDialog.jsx'
import { PageHeader } from '../components/ui/PageHeader.jsx'
import { useTenant } from '../features/account/useTenant.js'
import { useAuth } from '../features/auth/useAuth.js'
import { createDraftKey } from '../features/drafts/draftKeys.js'
import { usePersistentDraft } from '../features/drafts/usePersistentDraft.js'
import { supportedTimezones } from '../features/machines/timezones.js'
import { MasterRecordDialog } from '../features/operationalMasters/MasterRecordDialog.jsx'
import { createUIStateKey } from '../features/uiState/uiStateKeys.js'
import { usePersistentUIState } from '../features/uiState/usePersistentUIState.js'
import { saveMachineModel, saveManufacturer, saveOperationalPerson } from '../services/supabase/operationalMasters.js'
import { loadSettings, manageBranch, updateAdvancedEconomics, updateMembership, updateOperationalPermissions, updateWorkspace } from '../services/supabase/settings.js'

const sections = [
  ['workspace', 'Workspace', Building2], ['branches', 'Branches', MapPin], ['members', 'Members & Roles', Users],
  ['permissions', 'Permissions', ShieldCheck], ['operations', 'Operations', Gauge], ['models', 'Machine Models', Workflow],
  ['advanced', 'Advanced', Settings2],
]
const capabilities = [
  ['operator_can_initialize_component', 'Initialize component lifecycle', false],
  ['operator_can_replace_component', 'Replace component', true],
  ['operator_can_create_purchase', 'Create Purchase', false],
  ['operator_can_receive_goods', 'Receive goods', false],
  ['operator_can_adjust_inventory', 'Inventory adjustment', false],
  ['operator_can_transfer_inventory', 'Inventory transfer', false],
  ['operator_can_log_errors', 'Log Errors', true],
]
const roleLabels = { owner: 'Owner', admin: 'Admin', technician: 'Technician', operator: 'Operator' }
const newRequestId = () => crypto.randomUUID()
const validSection = (value) => value && sections.some(([id]) => id === value.section)

function FormError({ error }) { return error ? <div className="form-error" role="alert">{error.message || error}</div> : null }

function WorkspaceDialog({ user, account, onClose, onSave }) {
  const initial = { name: account.name, defaultTimezone: account.default_timezone, clientRequestId: newRequestId() }
  const draft = usePersistentDraft({ draftKey: createDraftKey({ userId: user.id, accountId: account.id, feature: 'settings-workspace', entityId: account.id }), initialValue: initial, validate: (value) => value && typeof value.name === 'string' && typeof value.defaultTimezone === 'string' })
  const [busy, setBusy] = useState(false); const [error, setError] = useState(null)
  async function submit(event) { event.preventDefault(); if (!draft.value.name.trim()) return setError(new Error('Workspace name is required.')); setBusy(true); try { await onSave(draft.value); draft.clearDraft(); onClose() } catch (caught) { setError(caught) } finally { setBusy(false) } }
  return <BlockingDialog className="machine-dialog settings-dialog glass-surface" labelledBy="workspace-dialog-title" onClose={onClose} busy={busy}>
    <header className="dialog-header"><div className="dialog-heading"><span className="dialog-icon"><Building2 size={21} /></span><div><span className="card-kicker">Workspace profile</span><h2 id="workspace-dialog-title">Edit workspace</h2><p>Identity and default operational timezone.</p></div></div><button className="icon-button" type="button" onClick={onClose} disabled={busy} aria-label="Close"><X size={19} /></button></header>
    <form className="machine-form" onSubmit={submit}><div className="machine-form-body"><div className="form-grid"><label className="form-field form-field-wide"><span>Display name <b className="required-mark">*</b></span><input maxLength="120" value={draft.value.name} onChange={(event) => draft.updateDraft((current) => ({ ...current, name: event.target.value }))} /></label><label className="form-field form-field-wide"><span>Default timezone <b className="required-mark">*</b></span><input list="settings-timezones" value={draft.value.defaultTimezone} onChange={(event) => draft.updateDraft((current) => ({ ...current, defaultTimezone: event.target.value }))} /><datalist id="settings-timezones">{supportedTimezones().map((zone) => <option key={zone} value={zone} />)}</datalist><small>Used only when a branch and machine do not have explicit overrides.</small></label></div><FormError error={error} /></div>
      <footer className="dialog-actions form-action-footer"><button className="draft-reset-button" type="button" onClick={() => draft.resetDraft({ ...initial, clientRequestId: newRequestId() })} disabled={!draft.hasDraft || busy} aria-label="Reset draft"><RotateCcw size={15} />Reset draft</button><button className="secondary-button" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="primary-button" disabled={busy}>{busy && <LoaderCircle className="spin" size={16} />}Save workspace</button></footer>
    </form>
  </BlockingDialog>
}

function BranchDialog({ user, account, branch, onClose, onSave }) {
  const initial = { code: branch?.code ?? '', name: branch?.name ?? '', address: branch?.address ?? '', timezone: branch?.timezone ?? '', notes: branch?.notes ?? '', clientRequestId: newRequestId() }
  const draft = usePersistentDraft({ draftKey: createDraftKey({ userId: user.id, accountId: account.id, feature: 'settings-branch', entityId: branch?.id ?? 'new' }), initialValue: initial, validate: (value) => value && typeof value.code === 'string' && typeof value.name === 'string' })
  const [busy, setBusy] = useState(false); const [error, setError] = useState(null)
  const change = (field, value) => draft.updateDraft((current) => ({ ...current, [field]: value }))
  async function submit(event) { event.preventDefault(); if (!draft.value.code.trim() || !draft.value.name.trim()) return setError(new Error('Branch code and name are required.')); setBusy(true); try { await onSave(branch ? 'update' : 'create', draft.value, draft.value.clientRequestId); draft.clearDraft(); onClose() } catch (caught) { setError(caught) } finally { setBusy(false) } }
  return <BlockingDialog className="machine-dialog settings-dialog glass-surface" labelledBy="branch-dialog-title" onClose={onClose} busy={busy}><header className="dialog-header"><div className="dialog-heading"><span className="dialog-icon"><MapPin size={21} /></span><div><span className="card-kicker">Workspace structure</span><h2 id="branch-dialog-title">{branch ? 'Edit branch' : 'Create branch'}</h2><p>Codes are normalized and unique inside this workspace.</p></div></div><button className="icon-button" type="button" onClick={onClose} disabled={busy} aria-label="Close"><X size={19} /></button></header><form className="machine-form" onSubmit={submit}><div className="machine-form-body"><div className="form-grid"><label className="form-field"><span>Code *</span><input maxLength="32" value={draft.value.code} onChange={(event) => change('code', event.target.value)} /></label><label className="form-field"><span>Name *</span><input maxLength="120" value={draft.value.name} onChange={(event) => change('name', event.target.value)} /></label><label className="form-field form-field-wide"><span>Timezone <small>Optional override</small></span><input list="branch-timezones" value={draft.value.timezone} onChange={(event) => change('timezone', event.target.value)} /><datalist id="branch-timezones">{supportedTimezones().map((zone) => <option key={zone} value={zone} />)}</datalist></label><label className="form-field form-field-wide"><span>Address <small>Optional</small></span><textarea rows="2" value={draft.value.address} onChange={(event) => change('address', event.target.value)} /></label><label className="form-field form-field-wide"><span>Notes <small>Optional</small></span><textarea rows="2" value={draft.value.notes} onChange={(event) => change('notes', event.target.value)} /></label></div><FormError error={error} /></div><footer className="dialog-actions form-action-footer"><button className="draft-reset-button" type="button" onClick={() => draft.resetDraft({ ...initial, clientRequestId: newRequestId() })} disabled={!draft.hasDraft || busy} aria-label="Reset draft"><RotateCcw size={15} />Reset draft</button><button className="secondary-button" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="primary-button" disabled={busy}>{busy && <LoaderCircle className="spin" size={16} />}{branch ? 'Save branch' : 'Create branch'}</button></footer></form></BlockingDialog>
}

function MemberDialog({ member, onClose, onSave }) {
  const [role, setRole] = useState(member.role); const [busy, setBusy] = useState(false); const [error, setError] = useState(null)
  async function submit(event) { event.preventDefault(); setBusy(true); try { await onSave(member, role, member.status, newRequestId()); onClose() } catch (caught) { setError(caught) } finally { setBusy(false) } }
  return <BlockingDialog className="confirm-dialog settings-member-dialog glass-surface" labelledBy="member-dialog-title" onClose={onClose} busy={busy}><form onSubmit={submit}><div className="confirm-dialog-body"><span className="confirm-dialog-icon"><UserRound size={23} /></span><h2 id="member-dialog-title">Change {member.display_name}’s role</h2><p>Role changes take effect immediately. Historical actor snapshots remain unchanged.</p><label className="form-field"><span>Role</span><select value={role} onChange={(event) => setRole(event.target.value)}>{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><FormError error={error} /></div><footer className="dialog-actions"><button className="secondary-button" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? 'Saving…' : 'Change role'}</button></footer></form></BlockingDialog>
}

function ConfirmDialog({ title, message, confirmLabel, danger = false, onClose, onConfirm }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(null)
  async function confirm() { setBusy(true); try { await onConfirm(); onClose() } catch (caught) { setError(caught) } finally { setBusy(false) } }
  return <BlockingDialog className="confirm-dialog glass-surface" labelledBy="settings-confirm-title" onClose={onClose} busy={busy}><div className="confirm-dialog-body"><span className="confirm-dialog-icon"><Archive size={23} /></span><h2 id="settings-confirm-title">{title}</h2><p>{message}</p><FormError error={error} /></div><footer className="dialog-actions"><button className="secondary-button" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className={danger ? 'danger-button' : 'primary-button'} type="button" onClick={confirm} disabled={busy}>{busy ? 'Saving…' : confirmLabel}</button></footer></BlockingDialog>
}

function OverviewCard({ icon, label, value, detail, onClick }) { return <button type="button" className="settings-summary-card glass-surface" onClick={onClick}><span>{createElement(icon, { size: 19 })}</span><div><small>{label}</small><strong>{value}</strong><em>{detail}</em></div></button> }

export function SettingsPage({ navigate }) {
  const { user } = useAuth(); const { account, membership, refresh: refreshTenant } = useTenant(); const canManage = ['owner', 'admin'].includes(membership?.role)
  const sectionState = usePersistentUIState({ uiStateKey: createUIStateKey({ userId: user.id, accountId: account.id, feature: 'settings', entityId: 'section' }), initialValue: { section: 'workspace' }, validate: validSection })
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [notice, setNotice] = useState(null); const [dialog, setDialog] = useState(null); const [policyBusy, setPolicyBusy] = useState(false)
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { setData(await loadSettings({ accountId: account.id })) } catch (caught) { setError(caught) } finally { setLoading(false) } }, [account.id])
  useEffect(() => { if (canManage) refresh() }, [canManage, refresh])
  const section = sectionState.value.section
  const counts = useMemo(() => data ? { activeBranches: data.branches.filter((item) => item.is_active).length, activeMembers: data.members.filter((item) => item.status === 'active').length, models: data.models.filter((item) => item.is_active).length, components: data.components.filter((item) => item.is_active).length, profiles: data.profiles.filter((item) => item.is_active).length, locations: data.locations.filter((item) => item.is_active).length } : {}, [data])
  async function done(message, includeTenant = false) { if (includeTenant) await refreshTenant(); await refresh(); setNotice(message) }
  async function saveWorkspace(values) { await updateWorkspace({ accountId: account.id, values, clientRequestId: values.clientRequestId }); await done('Workspace settings saved. Explicit branch and machine timezone overrides were unchanged.', true) }
  async function saveBranch(action, values, requestId) { await manageBranch({ accountId: account.id, branch: dialog?.branch, action, values, clientRequestId: requestId }); await done(`Branch ${action === 'create' ? 'created' : 'updated'}.`, true) }
  async function mutateBranch(branch, action) { await manageBranch({ accountId: account.id, branch, action, clientRequestId: newRequestId() }); await done(`Branch ${action === 'archive' ? 'archived' : 'restored'} without moving or deleting historical data.`, true) }
  async function mutateMember(member, role, status, requestId = newRequestId()) { await updateMembership({ accountId: account.id, member, role, status, clientRequestId: requestId }); await done(`Membership ${status === 'suspended' ? 'suspended' : status === 'active' && member.status === 'suspended' ? 'reactivated' : 'updated'}.`) }
  async function togglePolicy(key) { const next = { ...data.policy, [key]: !data.policy[key] }; setPolicyBusy(true); try { const saved = await updateOperationalPermissions({ accountId: account.id, policy: next, clientRequestId: newRequestId() }); setData((current) => ({ ...current, policy: saved })); setNotice('Operational permission policy saved and enforced by the database.') } catch (caught) { setError(caught) } finally { setPolicyBusy(false) } }
  async function toggleAdvanced() { const enabled = !account.machine_economics_advanced_enabled; setPolicyBusy(true); try { await updateAdvancedEconomics({ accountId: account.id, enabled, clientRequestId: newRequestId() }); await done(`Advanced Machine Economics ${enabled ? 'enabled' : 'disabled'}. No operating-cost rows were created.`, true) } catch (caught) { setError(caught) } finally { setPolicyBusy(false) } }
  async function saveMaster(kind, record, values) { if (kind === 'person') await saveOperationalPerson({ accountId: account.id, personId: record?.id, values }); else if (kind === 'manufacturer') await saveManufacturer({ accountId: account.id, manufacturerId: record?.id, values }); else await saveMachineModel({ accountId: account.id, modelId: record?.id, values }); await done(`${kind === 'person' ? 'Operator / PIC' : kind === 'manufacturer' ? 'Manufacturer' : 'Machine model'} saved.`) }

  if (!canManage) return <div className="page-stack settings-page"><PageHeader eyebrow={`${account.name} · Settings`} title="Workspace administration" description="How this workspace is configured and who may perform operational work." /><div className="permission-banner"><ShieldCheck size={18} /><span>Settings is available to active Owners and Admins. Your {roleLabels[membership?.role] ?? 'current'} role has no administrative access.</span></div></div>
  return <div className="page-stack settings-page"><PageHeader eyebrow={`${account.name} · Control plane`} title="Settings" description="Configure workspace structure, membership, permissions, and stable operational defaults." />
    {notice && <div className="success-banner" role="status"><span>{notice}</span><button type="button" onClick={() => setNotice(null)}>Dismiss</button></div>}
    {error && <div className="embedded-error" role="alert"><strong>Settings could not be loaded.</strong><span>{error.message}</span><button className="secondary-button" type="button" onClick={refresh}>Try again</button></div>}
    <div className="settings-layout"><nav className="settings-section-nav glass-surface" aria-label="Settings sections">{sections.map(([id, label, icon]) => <button type="button" key={id} className={section === id ? 'selected' : ''} onClick={() => sectionState.setUIState({ section: id })}>{createElement(icon, { size: 17 })}<span>{label}</span></button>)}</nav>
      <main className="settings-panel">{loading ? <div className="settings-empty glass-surface"><RefreshCcw className="spin" size={24} /><strong>Loading Settings…</strong></div> : data && <>
        {section === 'workspace' && <><div className="settings-overview-grid"><OverviewCard icon={Building2} label="Workspace" value={account.name} detail="Active" onClick={() => setDialog({ type: 'workspace' })} /><OverviewCard icon={MapPin} label="Branches" value={`${counts.activeBranches} active`} detail={`${data.branches.length - counts.activeBranches} archived`} onClick={() => sectionState.setUIState({ section: 'branches' })} /><OverviewCard icon={Users} label="Members" value={`${counts.activeMembers} active`} detail={`${data.members.length} total`} onClick={() => sectionState.setUIState({ section: 'members' })} /><OverviewCard icon={Gauge} label="Default timezone" value={account.default_timezone} detail="Machine → branch → workspace" onClick={() => setDialog({ type: 'workspace' })} /></div><section className="settings-card glass-surface"><header><div><span className="card-kicker">Workspace profile</span><h2>{account.name}</h2><p>Changing this label affects future UI only. Tenant identity and historical snapshots remain unchanged.</p></div><button className="secondary-button" type="button" onClick={() => setDialog({ type: 'workspace' })}><Edit3 size={15} />Edit</button></header><dl className="settings-detail-list"><div><dt>Workspace code</dt><dd>{account.code}</dd></div><div><dt>Default timezone</dt><dd>{account.default_timezone}</dd></div><div><dt>Status</dt><dd><span className="scope-pill custom">Active</span></dd></div><div><dt>Advanced economics</dt><dd>{account.machine_economics_advanced_enabled ? 'On' : 'Off'}</dd></div></dl></section>{data.audit.length > 0 && <section className="settings-card glass-surface"><header><div><span className="card-kicker">Administration evidence</span><h2>Recent changes</h2></div><History size={18} /></header><div className="settings-audit-list">{data.audit.map((event) => <div key={event.id}><strong>{event.action.replaceAll('.', ' ')}</strong><span>{event.actor_name_snapshot} · {new Date(event.created_at).toLocaleString()}</span></div>)}</div></section>}</>}
        {section === 'branches' && <section className="settings-card glass-surface"><header><div><span className="card-kicker">Workspace structure</span><h2>Branches</h2><p>Archive referenced branches; history stays in place and no machines are moved.</p></div><button className="primary-button" type="button" onClick={() => setDialog({ type: 'branch', branch: null })}><Plus size={16} />Create branch</button></header><div className="settings-row-list">{data.branches.map((branch) => <article key={branch.id} className={!branch.is_active ? 'archived' : ''}><span className="settings-row-icon"><MapPin size={18} /></span><div><strong>{branch.name}</strong><span>{branch.code} · {branch.timezone || `Inherits ${account.default_timezone}`}</span>{branch.address && <small>{branch.address}</small>}</div><span className={`scope-pill ${branch.is_active ? 'custom' : 'archived'}`}>{branch.is_active ? 'Active' : 'Archived'}</span><div className="settings-row-actions"><button type="button" aria-label={`Edit ${branch.name}`} onClick={() => setDialog({ type: 'branch', branch })}><Edit3 size={15} /></button><button type="button" aria-label={`${branch.is_active ? 'Archive' : 'Restore'} ${branch.name}`} onClick={() => setDialog({ type: 'branch-status', branch, action: branch.is_active ? 'archive' : 'restore' })}>{branch.is_active ? <Archive size={15} /> : <RotateCcw size={15} />}</button></div></article>)}</div></section>}
        {section === 'members' && <section className="settings-card glass-surface"><header><div><span className="card-kicker">Access directory</span><h2>Members & Roles</h2><p>Auth credentials and email changes remain in Supabase Auth. Secure invitation infrastructure is not available yet.</p></div></header><div className="settings-row-list">{data.members.map((member) => <article key={member.membership_id} className={member.status !== 'active' ? 'archived' : ''}><span className="settings-row-icon"><UserRound size={18} /></span><div><strong>{member.display_name}</strong><span>{member.email}</span><small>Joined {new Date(member.accepted_at || member.created_at).toLocaleDateString()}</small></div><span className="scope-pill custom">{roleLabels[member.role]}</span><span className={`scope-pill ${member.status === 'active' ? 'custom' : 'archived'}`}>{member.status}</span><div className="settings-row-actions"><button type="button" aria-label={`Change ${member.display_name} role`} onClick={() => setDialog({ type: 'member-role', member })}><Edit3 size={15} /></button><button type="button" aria-label={`${member.status === 'active' ? 'Suspend' : 'Reactivate'} ${member.display_name}`} onClick={() => setDialog({ type: 'member-status', member })}>{member.status === 'active' ? <Archive size={15} /> : <RotateCcw size={15} />}</button></div></article>)}</div>{data.members.length <= 1 && <div className="settings-inline-note">No additional members yet. Invitations require a future secure Auth onboarding flow.</div>}</section>}
        {section === 'permissions' && <section className="settings-card glass-surface"><header><div><span className="card-kicker">DB-authoritative policy</span><h2>Operational permission matrix</h2><p>Fixed cells reflect system roles. Operator cells are account-level policy toggles.</p></div></header><div className="permission-matrix" role="table"><div className="permission-matrix-head" role="row"><strong>Capability</strong><span>Owner</span><span>Admin</span><span>Technician</span><span>Operator</span></div><div className="permission-matrix-row" role="row"><strong>Daily Counter</strong><span><Check /></span><span><Check /></span><span><Check /></span><span><Check /></span></div>{capabilities.map(([key, label, technician]) => <div className="permission-matrix-row" role="row" key={key}><strong>{label}</strong><span><Check /></span><span><Check /></span><span>{technician ? <Check /> : '—'}</span><span><label className="feature-switch matrix-switch"><input type="checkbox" checked={Boolean(data.policy[key])} disabled={policyBusy} onChange={() => togglePolicy(key)} aria-label={`Operator can ${label}`} /><span aria-hidden="true" /><strong>{data.policy[key] ? 'On' : 'Off'}</strong></label></span></div>)}<div className="permission-matrix-row" role="row"><strong>Manage Component Catalog / Settings</strong><span><Check /></span><span><Check /></span><span>—</span><span>—</span></div></div></section>}
        {section === 'operations' && <><section className="settings-card glass-surface"><header><div><span className="card-kicker">Stable defaults</span><h2>Operational behavior</h2><p>Multiple Daily Counter readings per day remain supported. Operator/PIC selection remains required.</p></div></header><dl className="settings-detail-list"><div><dt>Timezone resolution</dt><dd>Machine → Branch → {account.default_timezone}</dd></div><div><dt>Daily readings</dt><dd>Multiple chronological inputs</dd></div><div><dt>Operator / PIC</dt><dd>Required by current contract</dd></div><div><dt>Counter type</dt><dd>Machine model profile</dd></div></dl></section><section className="settings-card glass-surface"><header><div><span className="card-kicker">Operational directory</span><h2>Operators / PIC</h2></div><button className="primary-button" type="button" onClick={() => setDialog({ type: 'master', kind: 'person', record: null })}><Plus size={16} />Add person</button></header><div className="settings-row-list">{data.people.map((person) => <article key={person.id} className={!person.is_active ? 'archived' : ''}><span className="settings-row-icon"><UserRound size={18} /></span><div><strong>{person.name}</strong><span>{person.code || 'No code'}</span></div><span className={`scope-pill ${person.is_active ? 'custom' : 'archived'}`}>{person.is_active ? 'Active' : 'Archived'}</span><div className="settings-row-actions"><button type="button" aria-label={`Edit ${person.name}`} onClick={() => setDialog({ type: 'master', kind: 'person', record: person })}><Edit3 size={15} /></button></div></article>)}</div></section></>}
        {section === 'models' && <><section className="settings-overview-grid compact"><OverviewCard icon={Factory} label="Manufacturers" value={data.manufacturers.filter((item) => item.is_active).length} detail="Shared + workspace" onClick={() => setDialog({ type: 'master-picker', kind: 'manufacturer' })} /><OverviewCard icon={Workflow} label="Machine Models" value={counts.models} detail="Active models" onClick={() => setDialog({ type: 'master-picker', kind: 'model' })} /><OverviewCard icon={Boxes} label="Components" value={counts.components} detail="Manage in Components" onClick={() => navigate('/components')} /><OverviewCard icon={Gauge} label="Model Profiles" value={counts.profiles} detail="Manage in Components" onClick={() => navigate('/components')} /></section><section className="settings-card glass-surface"><header><div><span className="card-kicker">Administrative handoff</span><h2>Component Configuration</h2><p>Catalog and Model Profile CRUD remains in the Components module.</p></div><button className="primary-button" type="button" onClick={() => navigate('/components')}><Boxes size={16} />Manage Components</button></header></section><section className="settings-card glass-surface"><header><div><span className="card-kicker">Model directory</span><h2>Machine models & manufacturers</h2><p>The existing shared service and dialogs remain the single CRUD implementation.</p></div><div className="settings-header-actions"><button className="secondary-button" type="button" onClick={() => setDialog({ type: 'master-picker', kind: 'manufacturer' })}>Manufacturers</button><button className="primary-button" type="button" onClick={() => setDialog({ type: 'master-picker', kind: 'model' })}>Machine Models</button></div></header></section><section className="settings-card glass-surface"><header><div><span className="card-kicker">Inventory handoff</span><h2>Inventory Locations</h2><p>{counts.locations} active locations. Location CRUD remains in Inventory.</p></div><button className="secondary-button" type="button" onClick={() => navigate('/inventory')}><Package size={16} />Open Inventory</button></header></section></>}
        {section === 'advanced' && <section className="settings-card glass-surface advanced-setting-card"><header><span className="settings-feature-icon"><CircleDollarSign size={20} /></span><div><span className="card-kicker">Machine Economics</span><h2>Advanced Machine Economics</h2><p>Off: Standard economics only. On: Standard remains unchanged, plus Advanced Operating Costs and Full Contribution. Enabling does not create or backfill costs.</p></div><label className="feature-switch"><input type="checkbox" checked={Boolean(account.machine_economics_advanced_enabled)} disabled={policyBusy} onChange={toggleAdvanced} /><span /><strong>{account.machine_economics_advanced_enabled ? 'On' : 'Off'}</strong></label></header></section>}
      </>}</main></div>
    {dialog?.type === 'workspace' && <WorkspaceDialog user={user} account={account} onClose={() => setDialog(null)} onSave={saveWorkspace} />}
    {dialog?.type === 'branch' && <BranchDialog user={user} account={account} branch={dialog.branch} onClose={() => setDialog(null)} onSave={saveBranch} />}
    {dialog?.type === 'branch-status' && <ConfirmDialog title={`${dialog.action === 'archive' ? 'Archive' : 'Restore'} ${dialog.branch.name}?`} message={dialog.action === 'archive' ? 'The branch will stop accepting new operational assignments. Machines and all historical data remain in place.' : 'The branch becomes available for new operational assignments again.'} confirmLabel={dialog.action === 'archive' ? 'Archive branch' : 'Restore branch'} danger={dialog.action === 'archive'} onClose={() => setDialog(null)} onConfirm={() => mutateBranch(dialog.branch, dialog.action)} />}
    {dialog?.type === 'member-role' && <MemberDialog member={dialog.member} onClose={() => setDialog(null)} onSave={mutateMember} />}
    {dialog?.type === 'member-status' && <ConfirmDialog title={`${dialog.member.status === 'active' ? 'Suspend' : 'Reactivate'} ${dialog.member.display_name}?`} message={dialog.member.status === 'active' ? 'Operational access stops immediately. Historical attribution remains visible. The database will block suspension of the last active Owner.' : 'The member regains access under their current role.'} confirmLabel={dialog.member.status === 'active' ? 'Suspend member' : 'Reactivate member'} danger={dialog.member.status === 'active'} onClose={() => setDialog(null)} onConfirm={() => mutateMember(dialog.member, dialog.member.role, dialog.member.status === 'active' ? 'suspended' : 'active')} />}
    {dialog?.type === 'master' && <MasterRecordDialog kind={dialog.kind} record={dialog.record} account={account} manufacturers={data.manufacturers} onClose={() => setDialog(null)} onSave={(values) => saveMaster(dialog.kind, dialog.record, values)} />}
    {dialog?.type === 'master-picker' && <BlockingDialog className="machine-dialog settings-dialog glass-surface" labelledBy="master-picker-title" onClose={() => setDialog(null)}><header className="dialog-header"><div className="dialog-heading"><span className="dialog-icon"><Workflow size={21} /></span><div><span className="card-kicker">Existing master</span><h2 id="master-picker-title">{dialog.kind === 'model' ? 'Machine Models' : 'Manufacturers'}</h2></div></div><button className="icon-button" type="button" onClick={() => setDialog(null)}><X size={19} /></button></header><div className="settings-picker-body"><button className="primary-button" type="button" onClick={() => setDialog({ type: 'master', kind: dialog.kind, record: null })}><Plus size={16} />Add {dialog.kind}</button><div className="settings-row-list">{(dialog.kind === 'model' ? data.models : data.manufacturers).map((record) => <article key={record.id}><span className="settings-row-icon">{dialog.kind === 'model' ? <Workflow size={18} /> : <Factory size={18} />}</span><div><strong>{record.name || record.id}</strong><span>{record.model_code || record.code || (record.account_id ? 'Workspace' : 'Shared')}</span></div>{record.account_id && <button className="secondary-button" type="button" onClick={() => setDialog({ type: 'master', kind: dialog.kind, record })}>Edit</button>}</article>)}</div></div></BlockingDialog>}
  </div>
}
