<?php
namespace Tests\Feature;
use App\Models\Account; use App\Models\AccountMembership; use App\Models\AccountMembershipBranch; use App\Models\Branch; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\DB; use Tests\TestCase;
class FoundationApiTest extends TestCase { use RefreshDatabase;
 public function test_health_and_version_are_safe(): void { $this->getJson('/api/v1/health')->assertOk()->assertJsonPath('data.status','ok'); $this->getJson('/api/v1/version')->assertOk()->assertJsonStructure(['data'=>['application','backend','git_sha','schema_batch']]); }
 public function test_login_me_and_logout(): void { $u=User::factory()->create(['password'=>'secret-password']); $this->postJson('/api/v1/auth/login',['identifier'=>$u->email,'password'=>'secret-password'])->assertOk(); $this->getJson('/api/v1/me')->assertOk()->assertJsonPath('data.user.id',$u->id); $this->postJson('/api/v1/auth/logout')->assertNoContent(); $this->getJson('/api/v1/me')->assertUnauthorized(); }
 public function test_anonymous_me_is_denied_and_uuid_contract_is_present(): void { $this->getJson('/api/v1/me')->assertUnauthorized(); $this->assertContains(strtolower(DB::getSchemaBuilder()->getColumnType('users','id')), ['char','varchar']); }
 public function test_anonymous_api_without_json_accept_is_still_a_deterministic_401(): void { $this->get('/api/v1/me')->assertUnauthorized()->assertJson(['message'=>'Unauthenticated.','errors'=>[]]); }
 public function test_authorized_empty_branch_inventory_returns_empty_state(): void { $u=User::factory()->create(['password'=>'secret-password']); $a=Account::create(['code'=>'EMPTY-INV','name'=>'Empty Inventory Account','status'=>'active']); $b=Branch::create(['account_id'=>$a->id,'code'=>'MAIN','name'=>'Main Branch','is_active'=>true]); $m=AccountMembership::create(['account_id'=>$a->id,'user_id'=>$u->id,'role'=>'owner','status'=>'active','accepted_at'=>now()]); AccountMembershipBranch::create(['account_id'=>$a->id,'membership_id'=>$m->id,'branch_id'=>$b->id,'is_active'=>true]); $this->postJson('/api/v1/auth/login',['identifier'=>$u->email,'password'=>'secret-password'])->assertOk(); $this->getJson("/api/v1/accounts/{$a->id}/branches/{$b->id}/inventory")->assertOk()->assertJsonPath('data.branchId',$b->id)->assertJsonCount(0,'data.items')->assertJsonCount(0,'data.locations')->assertJsonCount(0,'data.components')->assertJsonCount(0,'data.people')->assertJsonCount(0,'data.purchases')->assertJsonCount(0,'data.movements'); }
}
