<?php
namespace Tests\Feature;
use App\Models\{Account,AccountMembership,AccountMembershipBranch,Branch,PlatformUserPrivilege,User}; use App\Services\{AccountAccessResolver,BranchAccessResolver}; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Str; use Tests\TestCase;
class GovernanceParityTest extends TestCase { use RefreshDatabase;
 private function graph():array { $a=Account::create(['code'=>'A','name'=>'Account A','default_timezone'=>'Asia/Jakarta','status'=>'active']); $b=Account::create(['code'=>'B','name'=>'Account B','default_timezone'=>'Asia/Jakarta','status'=>'active']); $ba=$a->branches()->create(['code'=>'MAIN','name'=>'Main','is_active'=>true]); $bb=$b->branches()->create(['code'=>'MAIN','name'=>'Other','is_active'=>true]); $u=User::factory()->create(['username'=>'operator.a','status'=>'active']); $m=AccountMembership::create(['account_id'=>$a->id,'user_id'=>$u->id,'role'=>'operator','status'=>'active','accepted_at'=>now()]); AccountMembershipBranch::create(['account_id'=>$a->id,'membership_id'=>$m->id,'branch_id'=>$ba->id,'is_active'=>true]); return compact('a','b','ba','bb','u','m'); }
 public function test_username_login_and_disabled_user_are_generic_and_denied():void { $u=User::factory()->create(['username'=>'login.user','password'=>'secret-password','status'=>'active']); $this->postJson('/api/v1/auth/login',['login'=>'LOGIN.USER','password'=>'secret-password'])->assertOk(); $u->update(['status'=>'disabled']); $this->postJson('/api/v1/auth/login',['login'=>'login.user','password'=>'secret-password'])->assertUnprocessable()->assertJsonPath('errors.login.0','Invalid credentials.'); }
 public function test_cross_account_and_branch_access_fail_closed():void { $g=$this->graph(); $this->assertTrue(app(AccountAccessResolver::class)->canAccess($g['u'],$g['a'])); $this->assertFalse(app(AccountAccessResolver::class)->canAccess($g['u'],$g['b'])); $this->assertTrue(app(BranchAccessResolver::class)->canAccess($g['u'],$g['ba'])); $this->assertFalse(app(BranchAccessResolver::class)->canAccess($g['u'],$g['bb'])); }
 public function test_owner_is_not_platform_superuser_and_explicit_privilege_is_required():void { $g=$this->graph(); $g['m']->update(['role'=>'owner']); $this->assertFalse(app(\App\Services\PlatformPrivilegeService::class)->isSuperuser($g['u'])); PlatformUserPrivilege::create(['user_id'=>$g['u']->id,'role'=>'superuser','is_active'=>true]); $this->assertTrue(app(\App\Services\PlatformPrivilegeService::class)->isSuperuser($g['u'])); }
 public function test_suspended_membership_and_archived_account_deny_access():void { $g=$this->graph(); $g['m']->update(['status'=>'suspended']); $this->assertFalse(app(AccountAccessResolver::class)->canAccess($g['u'],$g['a'])); $g['m']->update(['status'=>'active']); $g['a']->update(['status'=>'archived']); $this->assertFalse(app(AccountAccessResolver::class)->canAccess($g['u'],$g['a'])); }
}
