import { apiClient, unwrapData, unwrapCollection } from '../../lib/api/apiClient.js'
import { unsupportedBackendOperation } from '../dataBackend.js'
export const catalogs = async () => unwrapCollection(await apiClient.get('/components'))
export const createCatalog = async (payload) => unwrapData(await apiClient.post('/components', payload))
export const profiles = async (modelId) => unwrapCollection(await apiClient.get(`/machine-models/${modelId}/profiles`))
export const createProfile = async (modelId, payload) => unwrapData(await apiClient.post(`/machine-models/${modelId}/profiles`, payload))
export const addSlot = async (profileId, payload) => unwrapData(await apiClient.post(`/model-profiles/${profileId}/slots`, payload))
export const machineComponents = async (machineId) => unwrapCollection(await apiClient.get(`/machines/${machineId}/components`))
export const sync = async (machineId) => unwrapData(await apiClient.post(`/machines/${machineId}/components/sync`))
export const addManual = async (machineId, payload) => unwrapData(await apiClient.post(`/machines/${machineId}/components/manual`, payload))
export const exclude = async (componentId, payload) => unwrapData(await apiClient.post(`/machine-components/${componentId}/exclude`, payload))
export const clearExclusion = async (exclusionId) => unwrapData(await apiClient.post(`/component-exclusions/${exclusionId}/clear`))
export const initializeLifecycle = async (componentId, payload) => unwrapData(await apiClient.post(`/machine-components/${componentId}/lifecycles`, payload))
export const unsupported = (operation) => { throw unsupportedBackendOperation('components', operation) }
export const loadComponentFoundation = async ({ accountId }) => ({ catalogs: await catalogs(accountId), profiles: [], machineComponents: [] })
export const adoptIntelligenceRecommendation = () => unsupported('adoptIntelligenceRecommendation')
export const saveComponent = (args) => args.component?.id ? unsupported('saveComponent') : createCatalog(args.values)
export const setComponentStatus = () => unsupported('setComponentStatus')
export const saveProfile = ({ modelId, values }) => createProfile(modelId, values)
export const setProfileStatus = () => unsupported('setProfileStatus')
export const addMachineComponent = ({ machineId, values }) => addManual(machineId, values)
export const removeMachineComponent = () => unsupported('removeMachineComponent')
export const clearMachineComponentExclusion = ({ machineId, profileId }) => unsupported('clearMachineComponentExclusion', machineId, profileId)
export const syncMachineComponents = (args) => sync(args.machineId)
export const reconcileManualComponent = () => unsupported('reconcileManualComponent')
export const getReconciliationCandidate = () => unsupported('getReconciliationCandidate')
