import { apiClient, unwrapData, unwrapCollection } from '../../lib/api/apiClient.js'

export async function loadOperationalIncidents({ accountId, branchId }) { const payload = await apiClient.get(`/accounts/${accountId}/branches/${branchId}/incidents`); return { incidents: payload.incidents ?? unwrapCollection(payload), members: payload.members ?? [], people: payload.people ?? [] } }
export async function loadOperationalIncident({ accountId, branchId, incidentId }) { const payload = await apiClient.get(`/accounts/${accountId}/branches/${branchId}/incidents/${incidentId}`); return { incident: payload.incident ?? unwrapData(payload), members: payload.members ?? [], revisions: payload.revisions ?? [], people: payload.people ?? [] } }
export async function createOperationalIncident({ accountId, branchId, values }) { const payload = await apiClient.post(`/accounts/${accountId}/branches/${branchId}/incidents`, values); return payload.incident ?? unwrapData(payload) }
const payload = (values) => ({ occurred_at: new Date(values.occurredAt).toISOString(), category: values.category, incident_type: values.incidentType, description: values.description, machine_id: values.machineId || null, operator_person_id: values.operatorPersonId || null, responsible_person_id: values.responsiblePersonId || null, invoice_number: values.invoiceNumber || null, customer_name_snapshot: values.customerName || null, product_name_snapshot: values.productName || null, qty_affected: values.qtyAffected === '' ? null : Number(values.qtyAffected), material_loss: values.materialLoss === '' ? 0 : Number(values.materialLoss), service_loss: values.serviceLoss === '' ? 0 : Number(values.serviceLoss), cause: values.cause || null, prevention: values.prevention || null, customer_resolution: values.customerResolution || null, change_reason: values.changeReason || 'Updated from incident detail' })
export async function updateOperationalIncident({ incidentId, values }) { const result = await apiClient.patch(`/incidents/${incidentId}`, payload(values)); return result.incident ?? unwrapData(result) }
export async function solveOperationalIncident({ incidentId, resolutionNote }) { const result = await apiClient.post(`/incidents/${incidentId}/solve`, { resolution_note: resolutionNote || null }); return result.incident ?? unwrapData(result) }
export async function resolveOperationalIncident({ incidentId }) { return solveOperationalIncident({ incidentId, resolutionNote: null }) }
export async function voidOperationalIncident({ incidentId, reason }) { const result = await apiClient.post(`/incidents/${incidentId}/void`, { void_reason: reason }); return result.incident ?? unwrapData(result) }
