import { apiClient, unwrapCollection, unwrapData } from '../../lib/api/apiClient.js'
export async function loadOperationalPeopleForBranch({ branchId }) { return unwrapCollection(await apiClient.get(`/branches/${branchId}/operational-people`)) }
export async function loadOperationalMasters({ accountId }) { const [people, manufacturers, models] = await Promise.all([apiClient.get(`/accounts/${accountId}/operational-people?per_page=100`), apiClient.get(`/manufacturers?account_id=${accountId}`), apiClient.get(`/machine-models?account_id=${accountId}`)]); return { people: unwrapCollection(people), manufacturers: unwrapCollection(manufacturers), models: unwrapCollection(models) } }
export async function saveOperationalPerson({ accountId, personId, values }) { const payload = { name: values.name, code: values.code, linked_user_id: values.linkedUserId || null, is_active: values.isActive ?? true }; return unwrapData(await (personId ? apiClient.put(`/accounts/${accountId}/operational-people/${personId}`, payload) : apiClient.post(`/accounts/${accountId}/operational-people`, payload))) }
export async function deleteOperationalPerson({ personId }) { return unwrapData(await apiClient.patch(`/operational-people/${personId}/status`, { is_active: false })) }
export async function saveManufacturer({ accountId, manufacturerId, values }) { const payload = { name: values.name, code: values.code, notes: values.notes || null, account_id: accountId }; return unwrapData(await (manufacturerId ? apiClient.put(`/manufacturers/${manufacturerId}`, payload) : apiClient.post('/manufacturers', payload))) }
export async function setManufacturerStatus({ manufacturerId, isActive }) { return unwrapData(await apiClient.patch(`/manufacturers/${manufacturerId}/status`, { is_active: isActive })) }
export const deleteManufacturer = ({ manufacturerId }) => setManufacturerStatus({ manufacturerId, isActive: false })
export async function saveMachineModel({ accountId, modelId, values }) { const payload = { name: values.name, model_code: values.modelCode, manufacturer_id: values.manufacturerId, machine_category: values.machineCategory, color_capability: values.colorCapability, description: values.description || null, notes: values.notes || null, account_id: accountId }; return unwrapData(await (modelId ? apiClient.put(`/machine-models/${modelId}`, payload) : apiClient.post('/machine-models', payload))) }
export async function setMachineModelStatus({ modelId, isActive }) { return unwrapData(await apiClient.patch(`/machine-models/${modelId}/status`, { is_active: isActive })) }
export const deleteMachineModel = ({ modelId }) => setMachineModelStatus({ modelId, isActive: false })
