<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
 Schema::table('users',function(Blueprint $t){$t->string('username',32)->nullable()->unique()->after('email');$t->string('status',16)->default('active')->index()->after('password');});
 Schema::table('accounts',function(Blueprint $t){$t->char('default_currency',3)->default('IDR')->after('default_timezone');$t->text('notes')->nullable();});
 Schema::table('branches',function(Blueprint $t){$t->text('address')->nullable()->after('name');$t->text('notes')->nullable();});
 Schema::table('account_memberships',function(Blueprint $t){$t->timestamp('invited_at')->useCurrent();$t->timestamp('accepted_at')->nullable();});
 Schema::create('account_membership_branches',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('account_id')->constrained()->restrictOnDelete();$t->foreignUuid('membership_id')->constrained('account_memberships')->restrictOnDelete();$t->foreignUuid('branch_id')->constrained()->restrictOnDelete();$t->boolean('is_active')->default(true)->index();$t->timestamps();$t->unique(['membership_id','branch_id'],'membership_branch_unique');$t->index(['account_id','branch_id','membership_id'],'membership_branch_scope_idx');$t->engine='InnoDB';});
 Schema::create('governance_audit_logs',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('actor_user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('action',80);$t->string('target_type',80);$t->uuid('target_id')->nullable();$t->foreignUuid('account_id')->nullable()->constrained()->nullOnDelete();$t->json('metadata')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['account_id','created_at']);$t->engine='InnoDB';});
 } public function down():void{Schema::dropIfExists('governance_audit_logs');Schema::dropIfExists('account_membership_branches');Schema::table('account_memberships',fn(Blueprint $t)=>$t->dropColumn(['invited_at','accepted_at']));Schema::table('branches',fn(Blueprint $t)=>$t->dropColumn(['address','notes']));Schema::table('accounts',fn(Blueprint $t)=>$t->dropColumn(['default_currency','notes']));Schema::table('users',fn(Blueprint $t)=>$t->dropColumn(['username','status']));}};
