import { Archive, Building2, CalendarCheck, Edit3, Eye, PackageCheck, Plus, ReceiptText, Trash2 } from 'lucide-react'
import { createUIStateKey } from '../uiState/uiStateKeys.js'
import { usePersistentUIState } from '../uiState/usePersistentUIState.js'

const sections = [{ id: 'purchases', label: 'Purchases', icon: PackageCheck }, { id: 'suppliers', label: 'Suppliers', icon: Building2 }, { id: 'receiving', label: 'Receiving', icon: ReceiptText }]
const money = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 2 })
const quantity = (value) => Number(value ?? 0).toLocaleString('id-ID', { maximumFractionDigits: 4 })
const validSection = (value) => value && sections.some((section) => section.id === value.section) && typeof value.showArchivedSuppliers === 'boolean'

function PurchaseList({ purchases, canManage, onCreate, onOpen }) {
  return <><div className="inventory-section-toolbar"><div><span className="card-kicker">Commercial evidence</span><h2>{purchases.length} purchases</h2><p>Purchases record quantity and price. Stock changes only when goods are received.</p></div>{canManage && <button className="primary-button" type="button" onClick={onCreate}><Plus size={16} />Create purchase</button>}</div>
    {purchases.length === 0 ? <div className="inventory-empty"><PackageCheck size={25} /><strong>No purchases recorded.</strong><span>Create a purchase without changing stock, then receive physical goods later.</span></div> : <div className="purchase-list"><div className="purchase-list-head"><span>Purchase</span><span>Supplier</span><span>Items</span><span>Total</span><span>Receiving</span><span>Status</span><span></span></div>{purchases.map((purchase) => <article key={purchase.purchase_id}><div><strong>{purchase.purchase_number}</strong><span>{new Date(`${purchase.purchase_date}T00:00:00`).toLocaleDateString('id-ID')}</span></div><div><strong>{purchase.supplier_name_snapshot}</strong><span>{purchase.supplier_reference || purchase.supplier_code_snapshot}</span></div><div><strong>{purchase.line_count}</strong><span>line{purchase.line_count === 1 ? '' : 's'}</span></div><div><strong>{money.format(Number(purchase.purchase_total))}</strong><span>{purchase.currency_code} evidence</span></div><div><strong>{quantity(purchase.receiving_progress_percent)}%</strong><span>{purchase.fully_received_line_count} / {purchase.line_count} lines complete</span></div><span className={`purchase-status status-${purchase.status}`}>{purchase.status.replaceAll('_', ' ')}</span><button className="icon-button" type="button" onClick={() => onOpen(purchase)} aria-label={`Open ${purchase.purchase_number}`}><Eye size={16} /></button></article>)}</div>}
  </>
}

function SupplierList({ suppliers, showArchived, canManage, onCreate, onEdit, onDelete }) {
  const visible = suppliers.filter((supplier) => showArchived ? !supplier.is_active : supplier.is_active)
  return <><div className="inventory-section-toolbar"><div><span className="card-kicker">Supplier master</span><h2>{visible.length} {showArchived ? 'archived' : 'active'} suppliers</h2><p>Supplier identities are workspace-owned and snapshotted into purchase history.</p></div>{canManage && <button className="primary-button" type="button" onClick={onCreate}><Plus size={16} />Add supplier</button>}</div>{visible.length === 0 ? <div className="inventory-empty"><Building2 size={25} /><strong>No {showArchived ? 'archived' : 'active'} suppliers.</strong><span>Owner/admin can maintain account-scoped supplier records here.</span></div> : <div className="supplier-list">{visible.map((supplier) => <article className={supplier.is_active ? '' : 'archived'} key={supplier.id}><span className="inventory-item-icon"><Building2 size={18} /></span><div><strong>{supplier.name}</strong><span>{supplier.supplier_code}{supplier.contact_person ? ` · ${supplier.contact_person}` : ''}</span><small>{supplier.email || supplier.phone || supplier.address || 'No contact details'}</small></div>{!supplier.is_active && <span className="scope-pill archived"><Archive size={12} />Archived</span>}{canManage && <div className="inventory-row-actions"><button type="button" onClick={() => onEdit(supplier)} aria-label={`Edit ${supplier.name}`}><Edit3 size={15} /></button><button type="button" onClick={() => onDelete(supplier)} aria-label={`Delete ${supplier.name}`}><Trash2 size={15} /></button></div>}</article>)}</div>}</>
}

function ReceiptList({ receipts, timeZone }) {
  const formatter = new Intl.DateTimeFormat('id-ID', { timeZone: timeZone || 'Asia/Jakarta', dateStyle: 'medium', timeStyle: 'short' })
  return receipts.length === 0 ? <div className="inventory-empty"><CalendarCheck size={25} /><strong>No receiving history.</strong><span>Posted physical receipts will appear here with immutable purchase-cost evidence.</span></div> : <div className="receipt-history-list">{receipts.map((line) => <article key={line.receipt_line_id}><span className="movement-direction movement-in"><CalendarCheck size={17} /></span><div><strong>{line.item_name_snapshot}</strong><span>{line.item_sku_snapshot} · {line.receipt_number}</span></div><div><span>Received</span><strong>+{quantity(line.quantity)} {line.unit_snapshot}</strong></div><div><span>Purchase</span><strong>{line.purchase_number_snapshot}</strong><small>{line.supplier_name_snapshot}</small></div><div><span>Acquisition price</span><strong>{money.format(Number(line.unit_price_snapshot))}</strong><small>{money.format(Number(line.acquisition_value))} received value</small></div><div><span>Location / PIC</span><strong>{line.location_name}</strong><small>{line.operational_person_name_snapshot}</small></div><time>{formatter.format(new Date(line.received_at))}</time></article>)}</div>
}

export function PurchasingPanel({ userId, account, data, canManage, onCreateSupplier, onEditSupplier, onDeleteSupplier, onCreatePurchase, onOpenPurchase }) {
  const key = createUIStateKey({ userId, accountId: account.id, feature: 'inventory-purchasing-view', entityId: 'workspace' })
  const state = usePersistentUIState({ uiStateKey: key, initialValue: { section: 'purchases', showArchivedSuppliers: false }, validate: validSection })
  return <div className="purchasing-workspace"><div className="purchasing-subtabs" role="tablist" aria-label="Purchasing sections">{sections.map((section) => <button key={section.id} type="button" role="tab" aria-selected={state.value.section === section.id} className={state.value.section === section.id ? 'selected' : ''} onClick={() => state.setUIState((current) => ({ ...current, section: section.id }))}><section.icon size={15} />{section.label}{section.id === 'receiving' && <span>{data.receipts.length}</span>}</button>)}</div>{state.value.section === 'suppliers' && canManage && <div className="inventory-record-toggle"><button className={!state.value.showArchivedSuppliers ? 'selected' : ''} onClick={() => state.setUIState((current) => ({ ...current, showArchivedSuppliers: false }))}>Active</button><button className={state.value.showArchivedSuppliers ? 'selected' : ''} onClick={() => state.setUIState((current) => ({ ...current, showArchivedSuppliers: true }))}>Archived</button></div>}<div className="purchasing-content">
    {state.value.section === 'purchases' && <PurchaseList purchases={data.purchases} canManage={canManage} onCreate={onCreatePurchase} onOpen={onOpenPurchase} />}
    {state.value.section === 'suppliers' && <SupplierList suppliers={data.suppliers} showArchived={state.value.showArchivedSuppliers} canManage={canManage} onCreate={onCreateSupplier} onEdit={onEditSupplier} onDelete={onDeleteSupplier} />}
    {state.value.section === 'receiving' && <ReceiptList receipts={data.receipts} timeZone={account.default_timezone} />}
  </div></div>
}
